### ISSUE TITLE
Animal accident data in the new forest

### ISSUE THREAD

**Issue by Carossta** [alphagov/tech-and-data-standards#35]
Publishinganimal accidents data as open data!

Animal accidents involving livestock have been reducing but there has been some interesting ideas from local councillors to reduce them further, such as stopping the free roaming of commoners livestock, which would have serious implications to tourism. I think that by opening up the animal accident data and publishing reusable information could lead to both innovative ideas to reducing animal accidents involving vehicles and also improve community engagement with the verderers and NFPA.Apologies I haven't followed the standard issue template buthopefully the link below will provide a bit of context!

https://callumrtanner.com/2017/01/16/open-up-the-data-of-animal-accidents-in-the-new-forest/

**Comment by Lawrence-G** [comment]
A good first step would be for this data to be available in a more open format (csv).
From a standards point of view, as you point out there’s room for more information to added to that which is already collected. That’s where I think an open standard for road traffic accident ( not just involving animals) reporting may be needed. Is there such a thing ? 

The Uk data service say on their site. “The credible monitoring of targeted reductions requires that data are reported consistently and accurately, and both national and local government, and local reporting police forces, work closely to achieve a common reporting standard”.
I have not found any information about that standard yet. It could be an internal standardising effort.  Does anyone know of such a standard?

**Comment by edent** [comment]
Do you have a contact at the New Forest? We might be able to convince them to release in a more open format.  That would probably be more suitable than finding a specific standard.

Looking at the PDFs, these appear to be high quality Excel exports. 
http://www.newforestnpa.gov.uk/downloads/file/1568/animal_accident_analysis_to_end_of_2016

**Comment by caltanner** [comment]
Hi Terence

No I don't unfortunately - as far as I can tell the verderers create and store the data, and then share this with the NFPA presumably in a reusable format because the NFPA seem to create some charts and graphs with the information.

verderers website is a bit old school but their policies section is pretty helpful in understanding the sort of stuff they get up to http://www.verderers.org.uk/policies.html and they also have a road accidents dataset themselves which actually conflicts with some of NFPA figures at times if I remember rightly,
 could be data handling issues. (http://www.verderers.org.uk/roadaccs.pdf)

It might be easiest to try and speak to NFPA but I think the Verderers would be the data owners/ controllers. There is also a multi-agency animal accident group which meets twice a year according to the verderers website and I thought it would be useful to nosey in on an upcoming meeting and get this on the agenda as a potential way of further reducing animal accidents (to start discussions about what they collect, how they collect it and why it might be useful if others outside of the verderers and NFPA could use this information)?

Would it be useful to map out was is currently being produced through the data, and what else could be produced in an ideal scenario? Wonder if you guys would have any ideas around this too.

Some ideas that popped into my head were:

Driver details where possible
Vehicle details
Road details (speed limit, condition, weather)
Whether the animal had a high vis collar (lots of the ponies end up with no high-vis collar, probably lost while trying to grab the tasty part of a bush!)
Animal details (type, age etc)
Date/Time

Obviously this is only for commoners livestock (pigs, cows, donkeys and horses) but there are plenty of types of deer (think there are at least four types of deer in the NewF) which would be covered by the Forestry Commission separately but they don't have any data on this (I think that was the response I had on twitter) but I would argue that it would be useful to have it all in one place, but practically sounds like that might be impossible.

Hope that isn't too much of a sidestep from the original question.... haha!

**Comment by Lawrence-G** [comment]
We are putting this issue on hold. It may be helped by the aims set out under the Local Digital Declaration.
