### ISSUE TITLE
A set of barcoding standards for the assets, people and places, across all care settings in England

### ISSUE THREAD

**Issue by itboyd** [alphagov/tech-and-data-standards#65]
# Create A Challenge

## Title
> A set of barcoding standards for the assets, people and places, across all care settings in England.

## Category
- Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
> NHS Digital is an executive non-departmental public body, accountable to the Secretary of State for Health and Social Care. We supply information and data to the health service, provide vital technological infrastructure, and help different parts of health and care work together. We are the guardians of patient data, making sure it's protected, and only ever used for the good of health and care. We also advise health and care on cyber and data security.

## Short Description
> GS1 is a global language for doing business. It is a set of uniform data structures that enable the unique coding of assets, people and places. Commonly used GS1 standards in healthcare include Global Trade Item Numbers (GTIN) to track products, Global Location Numbers (GLN) to identify locations in the NHS, and Global Service Relation Numbers (GSRN) to identify patients and clinicians.

## User Need
> The GS1 standards are used by the majority of NHS organisations and have also become the focus of the Dept of Health & Social Care (DHSC) initiative Scan4Safety. The project provides NHS trusts with the tools, financial backing and know-how to identify every patient, product and place within the healthcare setting using the GS1 global standards. 
This provides additional visibility of how care is administered to the patient, when and by whom. This, in turn leads to improved patient care and experience. 
Primary use cases:
•	Inventory management - enabling total stock visibility and precise ordering. It reduces wastage, out-of-stock situations and delivers cost savings and improved patient safety too
•	Purchase to pay - enabling automated matching of orders, invoices and delivery notes, reducing costs and speeding up subsequent payments
•	Product safety recall - enabling NHS organisations to quickly and effectively track and trace everything through their supply chain to individual patients. This saves hours of searching for recalled stock, releases more time back to care and, most importantly, enables recalled items to be removed before they reach a patient
Additional use cases:
•	eMedicines management 
•	Medical record management
•	Surgical instrument management
•	Community equipment management
•	Medical equipment management
•	Pathology sample management
•	Identifying babies from birth

## Expected Benefits
> The benefits of using the GS1 standards include:
•	A single depository of your data for the NHS
•	Reduced ship-to and bill-to enquiries
•	Fewer invoice queries and order disputes
•	Reduced transaction costs
•	Quicker released payments
•	Increased accuracy of vigilance reporting
•	Reduced wastage costs
•	Greater supply chain visibility
In 2015 an independent report by Lord Carter of Coles stated that, “The introduction of GS1 standards will allow every NHS hospital in England to save on average up to £3 million each year while improving patient care.”

## Functional Needs
> The functional needs which GS1 standards address include:
•	Utility - GS1 standards provide a consistent means to index, store, retrieve, and aggregate identification data across patients, practitioners, specialties and sites of care 
•	Interoperability - 
o	Patient identification - The unique identification of the patient enables accurate and consistent information to be captured and stored in the patient record at all relevant points along the patient pathway, a major addition to patient safety 
o	Catalogue management - A single national Product Information Management system for the NHS helps Trusts easily access accurate and transparent product information, enabling more accurate ordering, improved product availability and lower transaction costs. This helps drive efficiency and improved patient care
o	Location numbering - A single location numbering system, used by all Trusts and their suppliers, enables the unique and unambiguous identification of every physical and operational location within the healthcare system. This enables information to be collected and stored where an event occurs, whether this event involves the dispensing of patient care, the use of medical equipment or the ordering and delivery of goods
•	Governance - GS1 UK is an independent, not-for-profit organisation, with a community of over 36,000 members. They are one of 112 independent, not-for-profit GS1 organisations operating across 150 countries worldwide, with over two million members. The development of the GS1 standards development follows a defined global standards management process
•	Publication - The barcoding standards, GTIN, GLN and GSRN, are sublicensed by NHS Digital to any NHS organisation requiring a unique scannable code for its assets, people and places
•	Support - GS1 within the UK provides for access to technical groups, standards library, 'how to' guides, webinars, in person and online courses
•	Adoption - DHSCs eProcurement strategy mandates the use of GS1 standards in every NHS Acute Trust in England, as a means to increase efficiencies and significantly improve the quality and safety of care

**Comment by Lawrence-G** [comment]
**Brief assessment** [GS1](https://www.gs1uk.org/support/our-standards/general-specifications)

**Formal specification:**
Standards for item identity in supply chains enables interoperability of handling systems. 
**Implementation of the formal specification:**
Guidance is published and is freely available. 
**Openness:**
The full specification is available at no cost.
The standard advisory board and technical groups are open to all GS1 members 
GS1 members are granted a royalty free licence or a RAND licence for use of the specification. 
**Access to the formal specification:**
Freely available for download.
**Versatility/flexibility of the proposed standard:**
Widely used across all industries 
**End user effect of the formal specification:**
Strong support from different interest groups in the form of GS1 members.
GS1 standards are proven to increase efficiency in supply chains and organisations.
**Maintenance of the formal specification:**
GS1 is a not for profit organisation funded by membership its members in turn support and develop the standards
**Related European standards:**
none

**Comment by edent** [comment]
Regarding pricing and openness. It is free to read barcodes.  For generating codes, the situation is different. From https://www.gs1uk.org/get-a-barcode/frequently-asked-questions

> ### How does your pricing model work?
> As a not-for-profit organisation, we believe that the fairest fee structure is one based on turnover. This means that larger businesses pay more than smaller or new businesses to support the ongoing development and maintenance of the GS1 System. So, if you're a new or small business, you're paying our lowest fees. See our membership benefits page for further details on pricing.

And

> ### How do I get just one number?
> At the moment, this is not possible, except for specific cases of small music or charity organisations. We are reviewing our membership model though, to keep pace with the changing needs of our members.

This may present a barrier for Open Source and SMEs.  The [minimum fee](https://www.gs1uk.org/get-a-barcode/membership-benefits) is £119 +VAT.

**Comment by edent** [comment]
We've received this response from GS1. Posting here with their permission.

<hr>

1.  GS1 codes are free to decode. An SME or Open Source project (or anyone else for that matter) doesn't need to pay GS1 to decode or look up items
2.  GS1 membership, starting at £119 p.a.,  provides a licence to create all the GS1 identifiers (codes) that are typically required by an SME – these identifiers are globally unique and can be used with Application Identifiers so as to ensure positive identification
3.  Most manufacturers of medical devices and pharmaceuticals are already GS1 members in order to comply with FMD and UDI regulations (1.9m of the 2.2m medical devices listed on the US FDA GUDID database have GS1 identifiers)
4.  GS1 membership funds the free support and advice services provided to GS1 members
5.  GS1 is a membership organisation, governed by its members.  GS1 UK’s Supervisory Board is comprised of members, and the Board is elected by members.  The Supervisory Board is responsible for setting membership fees. On our [Supervisory Board](https://www.gs1uk.org/about-us/who-we-are/meet-our-teams/our-supervisory-board) today is a CEO of an NHS trust and until November the Commercial Director of DHSC was also a Board member
6.  Our [Healthcare Advisory Board](https://www.gs1uk.org/about-us/our-work-with-industry/advisory-boards/our-healthcare-advisory-board) is comprised of many senior NHS stakeholders who freely give up their valuable time to support our strategy direction and implementation

If I look at the UK Government definition of open standards:

**UK Gov defintion of open standards**

_[https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles#Defining-open-standards](https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles#Defining-open-standards)_

_Open standards give users permission to copy, distribute and use technology freely or at low cost._

_The Government only selects open standards for software interoperability, data and document formats that have:_

*   _collaboration between all interested parties, not just individual suppliers_
*   _a transparent and published decision-making process that is reviewed by subject matter experts_
*   _a transparent and published feedback and ratification process to ensure quality_

_Open standards must also be:_

*   _well documented, publicly available and free to use to provide fair access_
*   _mature, unless they are in the context of creating innovative solutions_
*   _supported by the market to demonstrate the independence of platforms, applications and vendors_
*   _released for use with a [royalty free licence](https://opensource.org/osr) which is irrevocable unless there is a breach of conditions_
*   _compatible with both [open source](https://opensource.org/licenses/alphabetical) and proprietary licensed solutions_

then GS1 standards seem to tick all the boxes. The fact that there is a small charge to create identifiers fits in with the “low cost”

Other points you may find of interest are:

1.  Documentation for all GS1 standards is openly available at no charge, this is in contrast to ISO and BSi standards. For SMEs keeping up to date with the latest ISO/BSI standards is likely to be as expensive as GS1 membership, even assuming they are aware the standards exist, know where to find them and can then understand them.. For example BS EN 1573:2015 Bar code. Multi industry transport label costs £170 reduced to £85 for BSi members (membership fee are not available on the web site). In addition GS1 members have access to free support for use of GS1 standards
2.  GS1 Membership fees are transparent and listed on line, are based on turnover with SME membership from £119 per annum. Membership fees fund the world wide local support which GS1 offers its members
3.  Standards only add value if they are widely adopted, implemented correctly and keep pace with changing needs.  The success of GS1 standards is in many ways because of the local support that GS1 offers  in virtually every country in the world. The membership fee funds that level of support, the alternative would be for users of GS1 standards to pay for advice in the open market which would be prohibitive for SMEs
4.  Members of GS1 have the ability to create large numbers of GS1 identifiers for no additional charge. For example an SME paying £119 per year can create more than enough GS1 identifiers for an SME as shown below
    1.  1,000 product identifiers
    2.  1,000 location identifiers
    3.  1,000 service relation numbers for staff and customer personnel
    4.  Virtually unlimited asset and shipment  identifiers – well over 1 billion of each

Remember that that the product identifier can be used on an unlimited number of physical products (we do not charge for each barcode produced!)

5.  System providers whether SME or not can build and sell systems based on GS1 standards without any payment.
6.  Manufacturers of medical devices and pharmaceuticals already must provide either  HIBBC or GS1 identifiers for the UDI and FMD, they have overwhelmingly chosen GS1 (1.9m of the 2.2m medical devices listed on the US FDA GUDID database have GS1 identifiers), even though HIBBC costs are lower than GS1 costs, for these companies there are no additional charges for using GS1 standards for other purposes; e.g. Open Source projects
7.  GS1 standards are voluntary
8.  Standards Development – Our Global community is continually refining and developing standards through the GSMP (Global Standards Management Process) which is a community-based forum for businesses facing similar problems to work together and develop standards-based solutions. Standards created by industry, for industry. A neutral participant, GS1 facilitates dialogue and the development of standards-based solutions among business and technical people from nearly sixty countries. Industries represented include retail and consumer goods, fresh foods, healthcare, transport and logistics, governments and many more. It should be noted that the GSMP and the Data Standards Board are completely open and do not require GS1 membership to participate

Within the NHS today, every baby born in a maternity ward in England is identified using GS1 standards, patient wristbands (ISB1077) have been mandated to carry the patient ID in GS1 standards format for many years, and most surgical instrument trays are also identified via GS1 standards.  NHS Digital has recently approved a Global Company Prefix (GCP) for OPCS codes and we are working collaboratively with the Apperta Foundation, the MHRA and other bodies.

**Comment by david-weatherby** [comment]
Although the topic title refers only to barcodes it should be pointed out that GS1 standards also cover the use of passive RFID. GS1 compliant barcodes and RFID tags are fully compatible allowing users to switch between technologies as appropriate for their applications. The data is the same whether sourced from a barcode scan or an RFID reader.

**Comment by ahepworth** [comment]
@Lawrence-G - As discussed, would just like to confirm the indemnification of GS1 barcode users against patent infringement for the use of barcodes.

**Comment by itboyd** [comment]
On Intellectual Property, paragraph 18.7 of GS1 UK T&C's - https://www.gs1uk.org/terms-and-conditions/intellectual-property-rights - addresses the responsibility of GS1 UK in respect of any third party claim of infringement of IP. As to Liability and Indemnity, paragragph 19.5 - https://www.gs1uk.org/terms-and-conditions/liability-and-indemnity - asserts that this is limited to the sum agreed in the service contract from which the liability arose. Therefore, the extent of GS1 UK's liability would be specific to each individual membership service contract. Paragraphs 20.1 & 20.2 - set the responsibility on the member to indemnify in full GS1 UK where the member is negligent through their own fault, error or omission.

**Comment by Lawrence-G** [comment]
A full assessment of the standard is being drafted [here](https://docs.google.com/document/d/1RZqDg0TM5oCThrByKXYiUNKmL1I1ItOv82_DUodKWsw/edit?usp=sharing). Comments are welcome.

**Comment by Lawrence-G** [comment]
Here is the GS1 barcode standards assessment 

## Formal Specification

**Q. 1.** Does it address and aid interoperability between public administrations?

**A.Yes**
GS1 codes act as persistent identification throughout a supply chain allowing information to be transferred from one system to another. 

**Q. 2.** Does it address and aid the development of digital services in government?

**A.Yes**
Where items are required to be identified consistently regardless of the number of service providers and different systems in a supply chain.

**Q. 3.** Are the functional and non-functional requirements for the use and implementation of the specification clearly defined?

**A.Yes**
All requirements are defined in the specification documents https://www.gs1uk.org/support/our-standards

**Q. 4.** Is it possible to implement the specification across different domains?

**A. Yes**
The GS1 Barcodes for use in healthcare GTIN GLN and GSRN are used in many different domains.

**Q. 5.** Is it largely independent from products of single providers, either open source or proprietary?

**A. Yes** 
Although only GS1 can produce barcodes which are licensed to users. Systems that use the barcodes are built by many different providers 

**Q. 6.** Is it largely independent from specific platforms?

**A. Yes**
GS1 barcodes are platform independent 

**Q. 7.** Has the standard been written so that it can be delivered or used with more than one technology (for example XML and JSON)?

**A.N/A** 
These are standards for barcodes 


**Q. 8.** Has the specification been sufficiently developed and existed long enough to overcome most of its initial problems?

**A.Yes**

**Q. 9.** Are there existing or planned mechanisms to assess its conformity and implementation - for example conformity tests, certifications and plugfests?

**A.Yes**
GS1, for example, provides tools to test barcode conformance https://www.gs1.org/services/check-digit-calculator
GS1 assess the conformity of products through a software certification program and publishes results on its website.

**Q. 10.** Does it have sufficient detail, consistency and completeness for the use and development of products?

**A.Yes**
The specification is aimed at suppliers and developers https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf
There are many products that use GS1 standards.

## Implementation of the formal specification

**Q. 11.** Does it provide current implementation guidelines and documentation for the implementation of products?

**A.Yes**
Guidelines are provided in the general specification document

**Q. 12**. Does it provide a reference (or open source) implementation?

**A.Yes**
GS1 Standards are core to the implementation of the DHSC programme, Scan4Safety. There are 6 demonstrator sites, lessons learned and ‘How To’ guides provided of the back of these implementations, see https://www.scan4safety.nhs.uk/

**Q. 13.** Does it address backwards compatibility with previous versions?

**A.Yes**
The GS1 approach is listed in the ‘GS1 Architecture Principles ‘ 
https://www.gs1.org/docs/architecture/GS1_Architecture_Principles.pdf
“The GS1 System Architecture shall be forward-looking and support adaptable, flexible solutions. It shall provide for migration strategies and backward compatibility.”

**Q. 14.** Are the underlying technologies for implementing it proven, stable and clearly defined?

**A.Yes**

## Openness

**Q. 15.** Is information on the terms and policies for the establishment and operation of the standardisation organisation publicly available?

**A.Yes**
In the Global Standard Management Process 
https://www.gs1.org/sites/default/files/docs/gsmp/gsmp_manual.pdf

**Q. 16.** Is participation in the creation process of the formal specification open to all relevant stakeholders (such as organisations, companies or individuals)?

**A.Yes**
Membership of the organisation gives access to the process. As stated by GS1 they develop standards “in partnership with the industry experts and business teams who actually use them”

**Q. 17.** Is information on the standardisation process publicly available?

**A.Yes**

The standardisation process is described in the Global Standards Management Process manual (GSMP) which is available for downloading.
https://www.gs1.org/docs/gsmp/gsmp_manual.pdf

**Q. 18.** Is information on the decision-making process for approving formal specifications is publicly available?

**A.Yes**
In the GSMP manual 
https://www.gs1.org/docs/gsmp/gsmp_manual.pdf

**Q. 19.** Are the formal specifications approved in a decision-making process which aims at reaching consensus?

**A.Yes**
Examples of how can be found in the GSMP and other documents produced by GS1. GS1 states that ‘Designed by consensus, our standards are proven, open and benefit from collaboration with respected global companies as well as local SME's’ https://www.gs1.org/about

**Q. 20.** Are the formal specifications reviewed using a formal review process with all relevant external stakeholders (such as public consultation)?

**A.Yes**
‘In Steps 2, 3, and 4 of the GSMP 4-Step Process, a workgroup creates a deliverable that is approved by the GSMP Community through an eBallot. Within each of these steps, the workgroup carries out the following sub-steps which are designed to drive towards progressively wider consensus.’ (GSMP) This process includes a 14 day community review stage when the GSMP community have the opportunity to comment on the draft and their comments to be acted on. 

**Q. 21.** Can all relevant stakeholders formally appeal or raise objections to the development and approval of formal specifications?

**A.Yes**
Objections can be made during development by workgroup and board members.

**Q. 22.** Is relevant documentation of the development and approval process of formal specifications publicly available (such as preliminary results and committee meeting notes)?

**A.Yes**
See the reports published here - https://www.gs1.org/standards/development/how-we-develop-standards/gsmp-reports

## Access to the formal specification

**Q. 23.** Is the documentation publicly available for implementation and use at zero or low cost?

**A.Yes**
https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf

**Q. 24.** Is the documentation of the intellectual property rights publicly available (is there a clear and complete set of licence terms)?

**A.Yes**
https://www.gs1uk.org/terms-and-conditions/intellectual-property-rights

**Q. 25.** Is it licensed on a royalty-free basis?

**A.Yes**
The IP policy states members ‘Receive a royalty-free license from Working group participants to Necessary Claims that cover requirements of GS1 standards’. There is a charge to create identifiers this charge is graded on the size of organisation the number of identifier codes produced and membership fee paid.
DHSC holds a contract with GS1 (UK) to cover its use by and fees for the NHS in England. The contract is managed by NHS Digital on behalf of DHSC.

## Versatility/flexibility of the proposed standard

**Q. 26.** Has the formal specification been used for different implementations by different vendors/suppliers?

**A.Yes**

**Q. 27.** Has the formal specification been used in different industries, business sectors or functions?

**A.Yes**
In many sectors including, retail, healthcare, transport and logistics and foodservice

**Q. 28.** Has interoperability been demonstrated across different implementations by different vendors/suppliers?

**A.Yes**
GS1 barcode standards are designed to be vender neutral and interoperable between different suppliers solutions. 

## End user effect of the formal specification

**Q. 29.** Do the products that implement it have a significant market share of adoption?

**A.Yes**

**Q. 30.** Do the products that implement it target a broad spectrum of end-uses?

**A.Yes**
GS1 standards are used in retail, foodservice, healthcare and other sectors

**Q. 31.** Does it have strong support from different interest groups?

**A.Yes**
GS1 UK has over 36,000 members from many different sectors. 

**Q. 32.** Is there evidence that the adoption of it supports improving efficiency and effectiveness of organisational process?

**A.Yes** 
GS1 publishes case stories of success in healthcare https://www.gs1uk.org/our-industries/healthcare/demonstrating-success-in-healthcare

See also the Carter report
https://www.gs1uk.org/our-industries/healthcare

**Q. 33.** Is there evidence that the adoption of it makes it easier to migrate between different solutions from different providers?

**A.Yes**
It is expected that migration between system be easier due to the number of suppliers that now support the standards 

**Q. 34.** Is there evidence that the adoption of it positively impacts the environment?

**A.Yes**
See results from Derby Teaching Hospital  ‘Culture change in terms of waste, opening and using only what’s needed’ 
https://www.gs1uk.org/our-industries/news/2016/12/13/gs1-standards-to-save-derby-teaching-hospitals-nhs-foundation-trust-over-1m

**Q. 35.** Is there evidence that the adoption of it positively impacts financial costs?

**A.Yes** 
See examples from NHS South of England procurement services
https://www.gs1uk.org/get-a-barcode/member-stories/between-the-lines-nhs

**Q. 36.** Is there evidence that the adoption of it positively impacts security?

**A.N/A**

**Q. 37.** Is there evidence that the adoption of it can be implemented alongside enterprise security technologies?

**A.N/A**

**Q. 38.** Is there evidence that the adoption of it positively impacts privacy?

**A.N/A**

**Q. 39.** Is it largely compatible with related (not alternative) formal specifications in the same area of application?

**A.N/A**

**Q. 40.** Is there evidence that the adoption of it positively impacts accessibility and inclusion?
**A.N/A**

## Maintenance of the formal specification

**Q. 41.** Does it have a defined maintenance organisation?

**A.Yes**
GS1 a not-for-profit organisation
https://www.gs1uk.org/about-us/who-we-are

**Q. 42.** Does the maintenance organisation provide sufficient finance and resource to control short-to-medium-term threats?

**A.Yes**
The latest report for GS1 UK is published here - https://www.gs1uk.org/~/media/documents/marketing-documents/gs1_uk_accounts_2017_18.pdf

**Q. 43.** Does the maintenance organisation have a public statement on intention to transfer responsibility for maintenance of it, if the organisation were no longer able to continue?

**A.Yes**
Paragraph 7 on page 4 of the UK Memorandum and Articles of Association; https://www.gs1uk.org/~/media/documents/marketing-documents/gs1ukmemorandumandarticlesofassociation.pdf?la=en, sets out the conditions on any outstanding assets of GS1 UK following its winding up or dissolution.

**Q. 44.** Does it have a defined maintenance and support process?

**A.Yes**
Through extensive training and online resources
https://www.gs1uk.org/support

**Q. 45.** Does it have a defined policy for version management?

**A.Yes** 
Migration  to new versions of standards is included in the Global Standards Management Process
(GSMP) Manual 
https://www.gs1.org/sites/default/files/docs/gsmp/gsmp_manual.pdf

## Related European standards

**Q. 46.** Is this an existing European standard or an identified technical specification in Europe? (Note: CEN, CENELEC or ETSI are the European standards bodies. Technical specifications provided by organisations other than CEN, CENELEC or ETSI can be under consideration to become a European standard or an identified technical specification in Europe.)

**A.No**
The barcode standards that GS1 produce are examples of ISO/CEN standards, and an EU CAMSS assessment of GS1 is available at; https://joinup.ec.europa.eu/release/camss-assessment-gs1/v100 

**Q. 47.** Does this specification or standard cover an area different from those already identified or currently under consideration as an identified European standard or specification?

**A.Yes**

**Comment by itboyd** [comment]
Thanks Lawrence

Ian Boyd

NHS Digital
07538 359892
ian.boyd@nhs.net<mailto:ian.boyd@nhs.net>

**Comment by Lawrence-G** [comment]
At the last Open Standards Board meeting, GS1 was described as very important for safety in hospitals, with the example given of product recalls that without GS1 would be very difficult to achieve. It is the only unique identifier for the products, people and places in hospitals and has a great part to play in the care of patients. While all the members agreed GS1 was vital and should be used it did not qualify as an open standard under the Board’s definition.
