### ISSUE TITLE
A diagnostics standard for the classification of each individual episode of care, across all care settings in England

### ISSUE THREAD

**Issue by itboyd** [alphagov/tech-and-data-standards#66]
# Create A Challenge

## Title
> A diagnostics standard for the classification of each individual episode of care, across all care settings in England.

## Category
-  Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
> NHS Digital is an executive non-departmental public body, accountable to the Secretary of State for Health and Social Care. We supply information and data to the health service, provide vital technological infrastructure, and help different parts of health and care work together. We are the guardians of patient data, making sure it's protected, and only ever used for the good of health and care. We also advise health and care on cyber and data security.

## Short Description
> The International Classification of Diseases (ICD) is the international standard diagnostic tool for epidemiology, health management and clinical purposes. The ICD was designed as a health care classification system, providing a system of diagnostic codes for classifying diseases, including classifications of a wide variety of signs, symptoms, abnormal findings, complaints, social circumstances, and external causes of injury or disease. This system is designed to map health conditions to corresponding generic categories together with specific variations, assigning for these a designated code. 

## User Need
> For the provider, commissioner, researcher and practitioner:
The ICD is used worldwide for morbidity and mortality statistics, reimbursement systems, and automated decision support in health care. This system is designed to promote international comparability in the collection, processing, classification, and presentation of these statistics. Within the NHS ICD-10 is used by all Clinical Coders to classify information derived from patient records, at the end of each hospital provided episode of care. There are currently over 19 million finished hospital episodes per year for admitted patient care in England. Once the information is coded using ICD-10, it is then used in an aggregated, non-identifiable form, to allow for statistical analysis.

## Expected Benefits
> The benefits of using ICD-10 include:
•	Comparable mortality and morbidity statistics overtime
•	Capturing a snapshot of population health at a point in time 
•	Monitoring and providing insight on health care trends
•	Informing public health investments
•	Aiding national and hospitals service planning
•	Reimbursing hospitals for the care provided

## Functional Needs
> The functional needs which ICD-10 addresses include:
•	Utility - In England, the uses of ICD-10 is defined in the NHS Data Model and Data Dictionary and specifically in the Admitted Patient Care Commissioning Data Set. It is also a vital component of several national datasets, including:
o	Hospital Episode Statistics (HES) in England
o	Patient Episode Data for Wales (PEDW)
o	Scottish Morbidity Records (SMR)
•	Interoperability – ICD-10 provides for consistent information classification and is fundamental to statistical analysis of healthcare. It also supports cross-mapping to other international standards, such as SNOMED CT
•	Governance - The ICD is published and maintained by the World Health Organization (WHO), the directing and coordinating authority for health within the United Nations. ICD-10 is the 10th revision of the ICD
•	Publication - For the UK ICD-10 was first mandated for use in 1995, being maintained and distributed by NHS Digital. In 2016, ICD-10 5th replaced the 4th Edition as the mandated diagnostic classification within the UK. For the UK SNOMED CT is maintained and distributed by NHS Digital. External governance is provided by the UK Strategy Board, which includes representation from England, Scotland, Wales and Northern Ireland. NHS Digital uses the Technology Reference data Update Distribution (TRUD) mechanism to license and distribute reference data on information standards to interested parties. It provides the release files, subsets, mappings and related documents for those using ICD-10 within their systems
•	Support - The WHO provides detailed information about ICD online, the ICD-10 online browser and some generic training materials. NHS Digital provides data files, technical documentation and online training materials,  NHS Digital also delivers a training programmes and qualifications to support ICD-10 within the NHS.
•	Adoption - ICD-10 is a fully implemented and embedded NHS standard, mandated for use by health care provider organisations. It forms part of the NHS Standard Contract and has been approved as an NHS fundamental information standard, by the The Data Coordination Board (DCB) and published under Section 250 of the Health and Social Care Act 2012

**Comment by Lawrence-G** [comment]
The Open Standards Team had a preview of this challenge and carried out a brief assessment of 
[ICD-10 ](http://apps.who.int/classifications/icd10/browse/2016/en)
**Formal specification:**
A coding standard for the recording of disease data. 
**Implementation of the formal specification:**
WHO produces reference and guidance for implementers
**Openness:**
A license is required to develop products that use the standard
**Access to the formal specification:**
Free to access by browser or API
**Versatility/flexibility of the proposed standard:**
Limited in its area of use
**End user effect of the formal specification:**
WHO members states are expected to provide disease classification data using ICD-10
**Maintenance of the formal specification:**
The standard has a transparent process. 
**Related European standards:**
This is a worldwide standard

All World Health Organization (WHO) Member States are expected to use the most current version of the ICD for reporting death and illness (according to an international treaty).

**Comment by Lawrence-G** [comment]
A draft of the full assessment of the standards is available[ here](https://docs.google.com/document/d/1RZd6Z7bWDIDY8teLlly7NTpQQsNXxMG0632JbG7lWdM/edit?usp=sharing). Comments are welcome

**Comment by Lawrence-G** [comment]
This is the assessment of ICD-10

## Formal specification

**Q.1** Does it address and aid interoperability between public administrations?

**Yes**
All four country administrations concerned with information with the mortality and morbidity of the population will be able to share data in a standard format with the ICD-10 standard.  It is a global standard with over 100 countries reporting in ICD.

**Q.2** Does it address and aid the development of digital services in government?

**Yes**
The alphanumeric codes allow easy storage, retrieval and analysis of health information.  By enabling the building of systems that can, for example, monitor health trends and statistics to plan spending. 

**Q.3** Are the functional and non-functional requirements for the use and implementation of the specification clearly defined?

**Yes** 
Requirements are defined in the WHO ICD instruction manual 
http://www.who.int/classifications/icd/ICD10Volume2_en_2010.pdf?ua=1

**Q.4** Is it possible to implement the specification across different domains?

**No**
The code list in ICD-10 is suitable for the domain of disease, and health problem recording counting of deaths as well as diseases, injuries, symptoms, reasons for encounter, factors that influence health status, and external cause of diseases.

**Q.5** Is it largely independent from products of single providers, either open source or proprietary?

**Yes**
The standard is not tied to a particular product.

**Q.6** Is it largely independent from specific platforms?

**Yes**
The standard is platform independent. 

**Q.7** Has the standard been written so that it can be delivered or used with more than one technology (for example XML and JSON)?

**Yes**
The codes in ICD-10 can be delivered by various technologies e.g. CSV or JSON.

**Q.8** Has the specification been sufficiently developed and existed long enough to overcome most of its initial problems?

**Yes**
The UK has a long history of using ICD for national and international reporting for morbidity and mortality statistics. ICD-10 was first used in 1995 and the latest edition was published in 2016.

**Q.9** Are there existing or planned mechanisms to assess its conformity and implementation - for example conformity tests, certifications and plugfests?

**Yes**
WHO provides online training in the standard: http://apps.who.int/classifications/apps/icd/icd10training/

NHS Digital provides various guidance resources including the NHS guidance: https://hscic.kahootz.com/connect.ti/t_c_home/grouphome

In England, the Data Security and Protection Toolkit provides criteria for regular quality inspections of coded clinical data for inpatient and day cases at hospital level and clinical coder training as part of the toolkit self-assessment 
https://hscic.kahootz.com/gf2.ti/f/762498/48490181.1/PDF/-/DataSecurityStandard1bigpicturedraftconsultationv1.15clinicalcodingauditguidance.pdf


**Q.10** Does it have sufficient detail, consistency and completeness for the use and development of products?

**Yes**
The standard describes the codes and how they should be used in Statistical presentation.



## Implementation of the formal specification

**Q.11** Does it provide current implementation guidelines and documentation for the implementation of products?

**N/A**
The standard is not intended for the building of dedicated products. There is information on use in the instruction manual that would be useful for building products.  

**Q.12** Does it provide a reference (or open source) implementation?

**Yes**
In England, this information standard is published under Section 250 of the Health and Social Care Act 2012.  ICD-10 is implemented across the UK four national countries and embedded in hospital Patient Administration Systems.  In the UK ICD-10 updates are supported by an Information Standards Notice, implementation timescales, and the Specification and Implementation Documents with detail for those who have to implement the information standard:
https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/scci0021-international-statistical-classification-of-diseases-and-health-related-problems-icd-10-5th-edition

**Q.13** Does it address backwards compatibility with previous versions?

**Yes**
A list of changes between versions is provided by WHO.  NHS Digital publishes Tables of Coding Equivalence for each version from 1995 to the current version 2016 version.

**Q.14** Are the underlying technologies for implementing it proven, stable and clearly defined?

**Yes**
**ICD-10** has been widely employed by technologies used across health since 1995.





## Openness

**Q.15** Is information on the terms and policies for the establishment and operation of the standardisation organisation publicly available?

**Yes**
The ICD is published and maintained by the World Health Organization (WHO).
https://www.who.int/about/who-we-are

**Q.16** Is participation in the creation process of the formal specification open to all relevant stakeholders (such as organisations, companies or individuals)?

**Yes**
The WHO includes a wide range of stakeholders including government agencies, service providers, professional organizations, NGOs, academic and research centres in the development of ICD: 
https://www.who.int/classifications/icd/revision/en/

**Q.17** Is information on the standardisation process publicly available?

**Yes**
Information is available on the WHO website.  Revisions to the standards are subject to endorsement by the World Health Assembly as part of the governance structure:
https://www.who.int/classifications/en
https://www.who.int/classifications/icd/revision/en/ Note: focus is on ICD-11 development

**Q.18** Is information on the decision-making process for approving formal specifications is publicly available?

**Yes**
Governance takes place through the World Health Assembly, which is the supreme decision-making body; and the Executive Board, which gives effect to the decisions and policies of the Health Assembly.  ICD-10 was endorsed by the WHA in May 1990 and came into effect in 1993: 
https://www.who.int/about/governance

**Q.19** Are the formal specifications approved in a decision-making process which aims at reaching consensus?

**Yes**
WHO has designated a number of Collaborating Centres to contribute to the work on the development, dissemination, maintenance and use of the WHO Family of International Classifications to support national and international health information systems, statistics and evidence. Selected NGOs in Official Relations with WHO and identified experts are also invited to contribute.  WHO receives the advice on how to process the proposals from the Family of International Classifications Network (WHOFIC) and various expert group listed on the WHO website.

**Q.20** Are the formal specifications reviewed using a formal review process with all relevant external stakeholders (such as public consultation)?

**Yes**
**ICD-10** was endorsed by the World Health Assembly in 1990 and came into effect in 1993 after public consultation.  The eleventh revision of the ICD is an example of the consultation and will be presented at the Seventy-Second World Health Assembly in May 2019:
http://www.who.int/features/2012/international_classification_disease/en/

**Q.21** Can all relevant stakeholders formally appeal or raise objections to the development and approval of formal specifications?

**Yes**
The World Health Organisation undertakes extensive preparation and consultation with all stakeholders to update and revise ICD-10.  

**Q.22** Is relevant documentation of the development and approval process of formal specifications publicly available (such as preliminary results and committee meeting notes)?

**Yes**
**ICD-10** is updated in consultation with the WHO network of Collaborating Centres for the family of classifications. The ICD development process is now managed on an open platform and stakeholders can raise objections to development proposals to the latest revision directly on the ICD-11 maintenance platform:
https://icd.who.int/
https://icd.who.int/dev11/l-m/en





## Access to the formal specification

**Q.23** Is the documentation publicly available for implementation and use at zero or low cost?

**Yes**
The ICD code list and supporting documentation are available online:
http://apps.who.int/classifications/icd10/browse/2016/en

NHD Digital also provide the data and documentation for UK implementation.

**Q.24** Is the documentation of the intellectual property rights publicly available (is there a clear and complete set of licence terms)?

**Yes**
The Licence terms are set out in the Licence Agreement available through NHS Digital distribution website, and these must be accepted to subscribe to the product:
https://isd.digital.nhs.uk/trud3/user/guest/group/0/pack/28/subpack/258/licences

**Q.25** Is it licensed on a royalty-free basis?

**Yes**
WHO is the copyright holder of ICD-10 and has granted to the Secretary of State a non-exclusive licence to review, abstract, quote and reproduce ICD-10 and to store ICD-10 in retrieval systems and transmit ICD-10 data by electronic, mechanical and other means for United Kingdom government purposes provided that WHO is acknowledged as the source.  WHO has further granted to the Secretary of State authority to grant non-exclusive sub-licences for United Kingdom government purposes to its suppliers in the United Kingdom, provided that WHO's copyright is appropriately acknowledged.  The licence is managed by NHS Digital on behalf of DHSC:
https://isd.digital.nhs.uk/trud3/user/guest/group/61/pack/28/subpack/258/licences



## Versatility/flexibility of the proposed standard

**Q.26** Has the formal specification been used for different implementations by different vendors/suppliers?

**Yes**
Yes, the standard has been integrated into the health information systems of many countries (more than 100). 

**Q.27** Has the formal specification been used in different industries, business sectors or functions?

**N/A**
ICD-10 is a standard for health information, specifically for morbidity and mortality data.

**Q.28** Has interoperability been demonstrated across different implementations by different vendors/suppliers?

**N/A**
The standard is used to compare the health of populations across WHO member nations.





## End user effect of the formal specification

**Q.29** Do the products that implement it have a significant market share of adoption?

**Yes**
Where ICD-10 is mandated for use within the health care estate of the UK, there will be widespread and consistent application of the standard within the various products which support the relevant areas of the estate. Therefore, the ICD-10 compliant products occupy the dominant share of the relevant market.

**Q.30** Do the products that implement it target a broad spectrum of end-users?

**Yes**
ICD-10 is employed within products used by those responsible for researching, planning, delivering and funding health care across the UK.

**Q.31** Does it have strong support from different interest groups?

**Yes**
The 194 Member States of the World Health Organization and includes a wide range of stakeholders including government agencies, service providers, professional organizations, NGOs, academic and research centres in the development of ICD.

**Q.32** Is there evidence that the adoption of it supports improving efficiency and effectiveness of organisational process?

**Yes**
WHO have global partnerships and initiatives such as: 
http://g2h2.org/watch-this/geneva-institutions/ghi/

**Q.33** Is there evidence that the adoption of it makes it easier to migrate between different solutions from different providers?

**Yes**
Where ICD-10 is mandated for use within the health care estate of the UK, there will be widespread and consistent application of the standard within the various products which support the relevant areas of the estate. Therefore, migration between products is eased through the application of ICD-10.

**Q.34** Is there evidence that the adoption of it positively impacts the environment?

**Yes**
WHO have many initiatives on use of ICD-10:
https://www.who.int/occupational_health/publications/en/oehicd10.pdf

**Q.35** Is there evidence that the adoption of it positively impacts financial costs?

**Yes**
ICD provides the diagnosis codes for Diagnosis-Related Groups (DRGs) used to categorize inpatient hospital visits severity of illness, risk of mortality, prognosis, treatment difficulty, need for intervention, and resource intensity.  DRGs are used by many countries.
In England, ICD provides underpinning diagnosis codes that support the generation of Healthcare Resource Groups (HRGs)  for National Tariff Payment System in England.

**Q.36** Is there evidence that the adoption of it positively impacts security?

**N/A**
ICD-10 is not designed or intended to enhance security, but it also places no restrictions on enhancing security through other standards or means.

**Q.37** Is there evidence that the adoption of it can be implemented alongside enterprise security technologies?

**N/A**
ICD-10 is not designed or intended to enhance security, but it also places no restrictions on enhancing security through other standards or means.

**Q.38** Is there evidence that the adoption of it positively impacts privacy?

**N/A**
ICD-10 is not designed or intended to enhance privacy, but it also places no restrictions on enhancing privacy through other standards or means.

**Q.39** Is it largely compatible with related (not alternative) formal specifications in the same area of application?

**Yes**
Maps are provided by NHS Digital between ICD-10 and the other UK data standards for health and care, such as SNOMED CT.

**Q.40** Is there evidence that the adoption of it positively impacts accessibility and inclusion?

**N/A**
ICD-10 is not designed or intended to enhance accessibility and inclusion, but it also places no restrictions on enhancing accessibility and inclusion through other standards or means.





## Maintenance of the formal specification

**Q.41** Does it have a defined maintenance organisation?

**Yes**
The World Health Organisation

**Q.42** Does the maintenance organisation provide sufficient finance and resource to control short-to-medium-term threats?

**Yes**
WHO is funded by Member States and publishes information on funding and spending: http://www.who.int/about/finances-accountability/reports/en/

**Q.43** Does the maintenance organisation have a public statement on an intention to transfer responsibility for maintenance of it, if the organisation were no longer able to continue?

**No**
WHO is a constituent part of the United Nations and if that were to fail then NHS Digital would continue to maintain ICD-10 on behalf of the UK.

**Q.44** Does it have a defined maintenance and support process?

**Yes**
Maintenance, development and support for the ICD standard is provided through membership, governance structure and mechanisms of the WHO Collaborating Centres for the family of classifications network.  NHS Digital is a UK WHO Collaborating Centre and provides support, training and helpdesk.

**Q.45** Does it have a defined policy for version management?

**Yes**
WHO publish official updates on their website for country implementation.  
In England, ICD-10 is an NHS Information Standard and updated versions are approved by the Data Coordination Board following scrutiny from the Data Standards Assurance Service (hosted by NHS Digital). Requirements are clearly defined for Health Care Providers in the Requirements Specification and Implementation Guidance of SCC10021:
https://digital.nhs.uk/data-and-information/information-standards/information-standards-and-data-collections-including-extractions/publications-and-notifications/standards-and-collections/scci0021-international-statistical-classification-of-diseases-and-health-related-problems-icd-10-5th-edition






## Related European standards

**Q. 46**. Is this an existing European standard or an identified technical specification in Europe? (Note: CEN, CENELEC or ETSI are the European standards bodies. Technical specifications provided by organisations other than CEN, CENELEC or ETSI can be under consideration to become a European standard or an identified technical specification in Europe.)

**Yes**
ICD-10 is an identified technical specification used for collection of Eurostat European Statistics:
https://ec.europa.eu/eurostat/search?p_auth=kE95qEIp&p_p_id=estatsearchportlet_WAR_estatsearchportlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_estatsearchportlet_WAR_estatsearchportlet_action=search&text=ICD-10

**Q. 47**. Does this specification or standard cover an area different from those already identified or currently under consideration as an identified European standard or specification?

**No**

**Comment by edent** [comment]
Brilliant work on this. Thanks!

**Comment by Lawrence-G** [comment]
At the last Open Standards Board meeting, ICD-10 was described as very important as the reporting of epidemiology data and analysing the health of populations enables better planning of health provision. It was noted that ICD-9 is still in use but mapping between the two standards is very good. As with SNOMED-CT the standards geographic limits was pointed out by the Board.
