### ISSUE TITLE
A single terminology standard for the direct management of an individual’s care, across all care settings in England

### ISSUE THREAD

**Issue by itboyd** [alphagov/tech-and-data-standards#67]
# Create A Challenge

## Title
> A single terminology standard for the direct management of an individual’s care, across all care settings in England.

## Category
-  Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
> NHS Digital is an executive non-departmental public body, accountable to the Secretary of State for Health and Social Care. We supply information and data to the health service, provide vital technological infrastructure, and help different parts of health and care work together. We are the guardians of patient data, making sure it's protected, and only ever used for the good of health and care. We also advise health and care on cyber and data security.

## Short Description
> SNOMED CT is a systematically organised computer processable collection of medical terms providing codes, terms, synonyms and definitions used in clinical documentation and reporting. SNOMED CT is the most comprehensive, multilingual clinical healthcare terminology in the world. Its primary purpose is to encode the meanings that are used in health information and to support the effective clinical recording, querying and retrieval of clinical data with the aim of improving patient care. SNOMED CT provides the core general terminology for Electronic Health Records (EHR). SNOMED CT’s comprehensive coverage includes: clinical findings, symptoms, diagnoses, procedures, body structures, organisms and other aetiologies, substances, pharmaceuticals, devices and specimens.

## User Need
> For the patient and the practitioner, SNOMED CT enables:
•	Recording clinical information at the level of detail needed for the provision of healthcare
•	Reducing errors and ensuring completeness of the initial digital data capture in a common way
•	Sharing already recorded data to reduce the need to repeat health history at each new encounter with a healthcare professional
•	Combining clinical information recorded by different people in different locations into simpler information views within a federated patient record
•	Writing rules for machine algorithms to run over the combined clinical information in order to influence health care delivery choices through alerts and triggers 
•	Decreasing the potential for differing human or machine interpretation of the combined patient information through use of a common and unambiguous terminology
•	Supporting quality, cost effective practice, research and future clinical guideline development
•	Effectively managing screening, treatment and patient follow up based on specified coded information
Example Use cases:
•	EHR systems
•	Computerised Provider Order Entry, such as E-Prescribing and E-Referral
•	Catalogues of clinical services, such as Diagnostic Imaging procedures
•	Knowledge databases used in clinical decision support systems 
•	Remote Intensive Care Unit monitoring
•	Laboratory test requesting and reporting
•	Emergency Room charting
•	Cancer reporting
•	Algorithms to identify at risk patients

## Expected Benefits
> The benefits of using SNOMED CT include:
•	Sharing vital information consistently within and across health and care settings
•	Providing greater depth of detail and content for all clinical specialities and professionals
•	Supporting clinical decision making
•	Enabling analysis for extensive clinical audit and research
•	Reducing the misinterpretation of the patient record in different care settings
•	Scaling benefits of using an international standard in place of existing UK-only ones

## Functional Needs
> The functional needs which SNOMED CT addresses include:
•	Utility - SNOMED CT can be used to directly record clinical details of individuals in an EHR. It provides a consistent means to index, store, retrieve, and aggregate clinical data across specialties and sites of care. It also helps in organising the content of EHR systems by reducing the variability in the way data is captured, encoded and used for clinical care of patients and research
•	Interoperability - SNOMED CT provides for consistent information interchange and is fundamental to an interoperable EHR. It also provides the user with linkages to clinical care pathways, shared care plans and other knowledge resources, to facilitate informed decision-making, and to support long-term patient care. It also supports cross-mapping to other international standards and classifications, such as ICD-10
•	Governance - SNOMED CT is maintained and distributed by SNOMED International, the trading name of the International Health Terminology Standards Development Organisation (IHTSDO), an international non-profit standards development organisation
•	Publication - For the UK SNOMED CT is maintained and distributed by NHS Digital. External governance is provided by the UK Strategy Board, which includes representation from England, Scotland, Wales and Northern Ireland. NHS Digital uses the Technology Reference data Update Distribution (TRUD) mechanism to license and distribute reference data on information standards to interested parties. It provides the release files, subsets, mappings and related documents for those using SNOMED CT UK Edition within their systems
•	Support - free coding tools and services exist that return a ranked list of SNOMED CT descriptors suitable for encoding any clinical report
•	Adoption - In England SNOMED CT is being deployed to GP practice systems in a phased approach from April 2018. Secondary care, acute care, mental health, community health, dentistry and other systems used in direct patient care must use SNOMED CT as the clinical terminology, before 1 April 2020

**Comment by Lawrence-G** [comment]
The Open Standards Team had a preview of this challenge and carried out a brief assessment of SNOMED CT. 
**Formal specification**
The standard is used in health data to code terminology. 
**Implementation of the formal specification**
Extensive guidance and tools are available.
**Openness**
License cost in non-member countries with certain exceptions. The standard development process is open to member contributions and all advisory group minutes published.
**Access to the formal specification**
The specification is available online to download and view.
**Versatility/flexibility of the proposed standard**
This is a specialist medical data standard for use primarily in electronic health records.
**End user effect of the formal specification**
We are unable to access in this report
**Maintenance of the formal specification**
The standard is well supported and should continue to be so.
**Related European standards**
No EU standard of similar scope. There may be some overlap in standards from [CEN/TC 251.](https://standards.cen.eu/dyn/www/f?p=204:32:0::::FSP_ORG_ID,FSP_LANG_ID:6232,25&cs=1FFF281A84075B985DD039F95A2CAB820)

A more detailed assessment is to follow.

**Comment by Lawrence-G** [comment]
A full assessment of the standard is being drafted [here](https://docs.google.com/document/d/1mNcAbuF9n3_RQaRZNfCoLJD2bA5HXOGgQzlb41Hg2TU/edit?usp=sharing). Comments are welcome.

**Comment by Lawrence-G** [comment]
This is the assessment of SNOMED CT

## Formal specification

**Q. 1.** Does it address and aid interoperability between public administrations?

**A. Yes** 
SNOMED CT will allow information to be ‘shared consistently within and across health and care settings’.

**Q. 2.** Does it address and aid the development of digital services in government?

**A. Yes**
Yes in any system that has to describe clinical information in individual and populations

**Q. 3.** Are the functional and non-functional requirements for the use and implementation of the specification clearly defined?

**A. YES**
These are documented in the Technical Implementation Guide 
https://ihtsdo.freshdesk.com/support/solutions/articles/4000010547-how-scalable-and-flexible-is-snomed-ct-domaincounries


**Q. 4.** Is it possible to implement the specification across different domains?

**A. YES**
SNOMED CT can be used to describe clinical terminology across different domains including different clinical domains 
(see report  https://www.sciencedirect.com/science/article/pii/S1532046412001530)

**Q. 5.** Is it largely independent from products of single providers, either open source or proprietary?

**A. Yes**
Products from many vendors use the standard.
https://www.snomed.org/our-customers/vendors/marketplace


**Q. 6.** Is it largely independent from specific platforms?

**A.Yes**
Not tied to any platform

**Q. 7.** Has the standard been written so that it can be delivered or used with more than one technology (for example XML and JSON)?

**A.Yes**
The format used in the specification is suitable for use with many technologies.  UTF-8 text is the standard for coding SNOMED CT

**Q. 8.** Has the specification been sufficiently developed and existed long enough to overcome most of its initial problems?

**A.Yes** 
In development since 1999 and used across the world

**Q. 9.** Are there existing or planned mechanisms to assess its conformity and implementation - for example conformity tests, certifications and plugfests?

**A.Yes** 

As SNOMED CT is continuously updated the standard’s authoring platform includes a validation tool for new content. 
There are various guidance resources including the NHS guidance-
https://hscic.kahootz.com/connect.ti/t_c_home/view?objectId=300147

**Q. 10.** Does it have sufficient detail, consistency and completeness for the use and development of products?

**A.Yes**
SNOMED CT has already been used in many products used in health care systems.

Implementation of the formal specification

**Q. 11.** Does it provide current implementation guidelines and documentation for the implementation of products?

**A. Yes**
International Health Terminology Standards Development Organisation publishes implementation guidance  https://confluence.ihtsdotools.org/display/DOCTIG 

NHS Digital’s guidance is available here - https://hscic.kahootz.com/connect.ti/t_c_home/viewcontent?contentid=301203&done=CONCreated

Examples of implementations using SNOMED CT are available in a dynamically maintained list at www.snomedinaction.org

**Q. 12.** Does it provide a reference (or open source) implementation?

**A. Yes**
NHS Digital publishes an open source reference implementation of one variant of SNOMED browsing, searching and reference value set maintenance functionality:
https://isd.digital.nhs.uk/trud3/user/guest/group/0/pack/7/subpack/98/releases

SNOMED International leads international collaboration on a range of open source tools and components more suited to Enterprise-scale implementation at https://github.com/IHTSDO

**Q. 13.** Does it address backwards compatibility with previous versions?

**A.Yes**
A statement from the SNOMED website gives an  example in the move from format 1 to format 2  “For backward compatibility Release Format 1 files can be generated using a conversion utility and continue to be distributed available during an interim transitional period” 

NHS Digital publishes data migration tools specifically for those still using the much older and now unlicensed SNOMED versions (SNOMED II, 3, 3.5 and RT), principally to be found within pathology and labs information systems across the world.

**Q. 14.** Are the underlying technologies for implementing it proven, stable and clearly defined?

**A.Yes**
SNOMED CT uses numerical codes suitable for records and databases. The SNOMED CT International Edition is released as a set of tab-delimited text files encoded in accordance with the Unicode UTF-8 specification.

## Openness

**Q. 15.** Is information on the terms and policies for the establishment and operation of the standardisation organisation publicly available?

**A.Yes**
See website here - https://www.snomed.org/our-organization/governance-and-advisory

**Q. 16.** Is participation in the creation process of the formal specification open to all relevant stakeholders (such as organisations, companies or individuals)?

**A.Yes**
Full voting membership of SNOMED International (prev. IHTSDO) is limited to agencies endorsed by an appropriate national government authority within member country. paying an annual subscription (https://www.snomed.org/our-stakeholders/members). Individuals and, groups and commercial entities are not eligible for membership, they but can, however, participate in SNOMED International activities through Advisory Groups, Special Interest Groups (SIGs), Project Groups, Vendor Forums etc.

**Q. 17.** Is information on the standardisation process publicly available?

**A.Yes**
An overview can be found in an FAQ - https://ihtsdo.freshdesk.com/support/solutions/articles/4000010563-how-is-snomed-developed-and-maintained-

And a scan of the documented process can be found here - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2244575/?page=2

**Q. 18.** Is information on the decision-making process for approving formal specifications is publicly available?

**A.Yes**
See the organisation information here for the process
https://confluence.ihtsdotools.org/display/DOCSTART/14.+The+Organization+Behind+SNOMED+CT


**Q. 19.** Are the formal specifications approved in a decision-making process which aims at reaching consensus?

**A.Yes**
As quoted in the [process documentation](https://confluence.ihtsdotools.org/display/DOCSTART/9.+Content+Development) ”Conflicts between editors are resolved through an iterative process, based on achieving agreement and consensus”

More technical changes to aspects of the standard, especially those materially likely to significantly affect existing implementations and deployments (such as the redesign of how the distributed content is encoded (RF2) and the timing of such changes), normally involve a significant period of impact assessment and consensus-building engagement with the community of practice, as per the organisation’s Major Change, but such aspects can ultimately change without a formal voting or balloting step.
https://confluence.ihtsdotools.org/display/PL/Product+Lifecycle+Home 

**Q. 20.** Are the formal specifications reviewed using a formal review process with all relevant external stakeholders (such as public consultation)?

**A.Yes**
Details of public consultations are published in SNOMEDs quarterly newsletter 

**Q. 21.** Can all relevant stakeholders formally appeal or raise objections to the development and approval of formal specifications?

**A.Yes**
This is possible via clinical engagement and advisory groups within SNOMED International's community of practice.
(https://www.snomed.org/our-customers/clinicians). The organisation is ultimately accountable to its Member Forum and General Assembly, which prioritises proposals of likely to be beneficial to the shared national informatics interests, and blocks those that could be disruptive.

**Q. 22.** Is relevant documentation of the development and approval process of formal specifications publicly available (such as preliminary results and committee meeting notes)?

**A.Yes**
Meeting notes from the various groups and bodies can be found at 
https://confluence.ihtsdotools.org/ 

## Access to the formal specification

**Q. 23.** Is the documentation publicly available for implementation and use at zero or low cost?

A.Yes
Yes, in the UK and the other Member States. A fee is payable for deployment outside that geographic boundary.
All subscription-paying Member States and citizens or bodies corporate thereof, plus all separately registered and so fee paying SNOMED Affiliates, have access to the International Release of SNOMED CT and all associated documentation for no further charge.
There are free open source browsers for use by organisations not ready to build their own tools and extensive documentation freely available here- 
https://browser.ihtsdotools.org/? for the purpose of exploring and evaluating the terminology only.
Other  documentation freely available here https://confluence.ihtsdotools.org/display/DOC

**Q. 24.** Is the documentation of the intellectual property rights publicly available (is there a clear and complete set of licence terms)?

**A.Yes**
SNOMED International does not charge for use of SNOMED CT in SNOMED International Member countries or territories. Charges may apply for affiliate use of SNOMED CT in non-Member territories
See affiliate licence - https://www.snomed.org/SNOMED/media/SNOMED/documents/IHTSDO-Affiliate-License-Agreement_UK_20180101_v1.pdf

**Q. 25.** Is it licensed on a royalty-free basis?

A. Yes within member states, no elsewhere 

Licensing to Member countries is conditional on payment of the annual subscription fee,  which is based on Gross National Income rather than actual usage. Sublicensing to citizens or bodies corporate within Member countries is free of additional charge. 

Deployment of SNOMED outside the geographic boundaries implied by the union of all current Member State territories, including by individuals or bodies corporate legally based within any current Member State, requires additional Licensing and an annual payment of a per-deployment volume licensing fee.
https://www.snomed.org/snomed-ct/get-snomed
The UK is a founder member of SNOMED International 

Versatility/flexibility of the proposed standard

**Q. 26.** Has the formal specification been used for different implementations by different vendors/suppliers?

**A.Yes**
See the published vendor list for products - https://www.snomed.org/our-customers/vendors/marketplace

**Q. 27**. Has the formal specification been used in different industries, business sectors or functions?

**A.No**
Heath and Social Care and Health Insurance sectors only (this is not a negative response given the nature of this standard), but therefore including by the healthcare components of many other sectors include e.g. Aerospace (NASA) and Defence (UK MoD)

**Q. 28.** Has interoperability been demonstrated across different implementations by different vendors/suppliers?

**A.Yes**
The standard is intended to facilitate the exchange of data across different systems and platforms, for example, different platforms used by health services that employ the standard in health records. It is already the lingua franca by which the NHS aggregates clinical summary information from 5 different Primary Care System vendors into a single Summary Care Record view, or transmits electronic prescriptions from multiple prescribing endpoints and systems to individual pharmacies.

## End user effect of the formal specification

**Q. 29.** Do the products that implement it have a significant market share of adoption?

**A.Yes**
SNOMED CT has a significant market share internationally and has 37 member nations. Within the NHS, it is on track to be the reference language used by all primary and secondary care clinical system vendor deployments by the end of 2019.

**Q. 30.** Do the products that implement it target a broad spectrum of end-users?

**A.Yes**
Within the health sector 

**Q. 31.** Does it have strong support from different interest groups?

**A.Yes**
SNOMED CT is in use in the health systems of at least 37 nations globally.

**Q. 32.** Is there evidence that the adoption of it supports improving efficiency and effectiveness of organisational process?

**A.Yes**
A report found that SNOMED CT was part of the solution to gaining “ benefits of semantic interoperability in health data”
http://assess-ct.eu/fileadmin/assess_ct/final_brochure/assessct_final_brochure.pdf

**Q. 33.** Is there evidence that the adoption of it makes it easier to migrate between different solutions from different providers?

**A.Yes**
No specific published evidence found, but the use of a standard code for clinical terms should make migration between systems easier. Historical NHS experience has certainly been that the significant cost and risk associated with a GP practice attempting to move between clinical system suppliers based on different coding systems has been strong disincentive to further moves between suppliers.

**Q. 34.** Is there evidence that the adoption of it positively impacts the environment?

**A.YES**
As part of a migration to digital records from a paper-based system.

**Q. 35.** Is there evidence that the adoption of it positively impacts financial costs?

**A.Yes**
Though we were unable to find figures for saving financial costs, several reports point to the long-term savings once an interoperable digital system is in place generating savings from time saved in handling clinical data and stakeholders only having to deal with one single terminology.

**Q. 36.** Is there evidence that the adoption of it positively impacts security?

**A.N/A**
This standard does not affect security directly

**Q. 37.** Is there evidence that the adoption of it can be implemented alongside enterprise security technologies?

**A.N/A**
SNOMED CT is not a security standard the information coded with the standard would rely on the security of the platform holding the data.

**Q. 38.** Is there evidence that the adoption of it positively impacts privacy?

**A.N/A**
No evidence of any effect on privacy found in our search.

**Q. 39.** Is it largely compatible with related (not alternative) formal specifications in the same area of application?

**A.Yes**
SNOMED CT Is mapped to other international standards including the WHO ICD standards LOINC and OPCS-4. It also supports ANSI, DICOM, HL7, and ISO standards.

**Q. 40.** Is there evidence that the adoption of it positively impacts accessibility and inclusion?

**A.No**
No evidence found of impact on inclusion and accessibility.

Note: SNOMED CT as a clinical data standard, does not directly attempt to address user accessibility and inclusion. By nature of being the means by which health and care information is better defined, shared and interpreted, it does enable those requesting or receiving health and care services to be more visible and better understood by those planning, directing and delivering services. 
Maintenance of the formal specification

**Q. 41.** Does it have a defined maintenance organisation?

**A.Yes**
SNOMED International 

**Q. 42.** Does the maintenance organisation provide sufficient finance and resource to control short-to-medium-term threats?

**A.Yes**
Through membership payments by member counties
The financial report is included in annual activity reports https://www.snomed.org/SNOMED/media/SNOMED/documents/IHTSDO-Annual-Activity-Report-2016.pdf

**Q. 43.** Does the maintenance organisation have a public statement on the intention to transfer responsibility for maintenance of it, if the organisation were no longer able to continue?

**A.Yes**

Note: Paragraph 10.1.2 on page 39 of the Articles of Association; http://www.snomed.org/SNOMED/media/SNOMED/documents/HTSDO-Articles-(English-company-limited-by-guarantee)-V2-2.pdf, sets out the conditions on any outstanding assets of SNOMED International following its winding up or dissolution.
Further, NHS Digital maintains the core international version of SNOMED CT as a UK version, as well as the UK specific extensions to the standard. If there were a failure of SNOMED International, NHS Digital can maintain SNOMED CT on behalf of the UK.

**Q. 44.** Does it have a defined maintenance and support process?

**A.Yes**
Maintenance and development for the standard is provided through the membership and governance structure and mechanisms of SNOMED International. There is a defined publication schedule for each update to the standard, currently biannual. Support is through SNOMED International’s  24hr Helpdesk.

**Q. 45.** Does it have a defined policy for version management?

**A.Yes**
Through the SNOMED change management process https://confluence.ihtsdotools.org/display/DOCCMG/1+Change+Management+Guide
See also the release schedule.
https://confluence.ihtsdotools.org/display/DOCSTART/13.+Release+Schedule+and+File+Formats

## Related European standards

**Q. 46.** Is this an existing European standard or an identified technical specification in Europe? (Note: CEN, CENELEC or ETSI are the European standards bodies. Technical specifications provided by organisations other than CEN, CENELEC or ETSI can be under consideration to become a European standard or an identified technical specification in Europe.)

**A.No**

Note: A report made for the EU by ASSESS CT 5 recommendations for members states and declares SNOMED CT is the best available core reference terminology for cross-border, national and regional eHealth deployments in Europe (Dec 2016).

**Q. 47.** Does this specification or standard cover an area different from those already identified or currently under consideration as an identified European standard or specification?

**A.Yes**

**Comment by itboyd** [comment]
Thanks Lawrence

Ian Boyd

NHS Digital
07538 359892
ian.boyd@nhs.net<mailto:ian.boyd@nhs.net>

**Comment by Lawrence-G** [comment]
The Open Standards Board discussed Snomed CT at the last meeting. It was thought that the standard as a complete terminology and ontology for healthcare is very important to replace systems that use vendor formatted data which hinders interoperability. As an international standard SNOMED allows data to be shared across borders. SNOMED CT is compatible with and will support healthcare systems moving to FHIR (Fast Healthcare Interoperability Resources). 
The Opens Standards Board supports the use of  SNOMED CT by the NHS. The members noted that the standard is outside the scope of the Board and the standard’s license limits use outside member states.
