### ISSUE TITLE
Unique Property Reference Number and Unique Street Reference Number

### ISSUE THREAD

**Issue by stevenbrandwood** [alphagov/tech-and-data-standards#68]
# Create A Challenge

## Title
> Unique Property Reference Number and Unique Street Reference Number

## Category
- [X] Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
> Steve Brandwood.  Executive Director of Engagement. GeoPlace.
Responsible for geographic information capacity building in local government through the Local Government Association.  Managed the procurement of geographic information on behalf of the sector as well as taking forward the National Land and Property Gazetteer and National Street Gazetteer initiatives. Lead advisor on local government geographic information.  Local government lead on setting up of GeoPlace - bringing local government and Ordnance Survey together in a joint venture.  Now responsible for GeoPlace's engagement with local government, wider stakeholder management, communications and marketing.

## Short Description
> To enable a standard way of defining and exchanging property and street information.
The Unique Property Reference Number (UPRN) and the Unique Street Reference Number (USRN) are attributed by local government to every address and street in GB.  These identifiers are used to link data and systems to ensure unambiguous and persistent identification, use and sharing of information related to streets and properties.  Embedded in local government and many other public sector bodies, the UPRN and USRN are already providing significant service delivery and efficiency benefits.  Ubiquitous use across the public sector will significantly increase these benefits. 
GeoPlace has been working with the Geospatial Commission to make ‘open’ the URPN and USRN with their appropriate geometries and are seeking to ‘mandate’ the use of these identifiers across government.

## User Need
> The Unique Property Reference Number (UPRN) and Unique Street Reference Number (USRN) are the unique identifier for every addressable location and street in Great Britain.  Allocated by local authorities, they provide a comprehensive, complete and consistent identifier throughout a street and property's life.
•	We instinctively use addresses and street names to communicate information about ourselves and the world around us, the UPRN and USRN performs the same role in digital data sharing.  The UPRN and USRN help to link internal datasets together and share information with other organisations who use the identifiers. Licenced users already using the identifiers include local and central government bodies, emergency services, platform providers, insurance, logistics providers and utility companies.
•	The UPRN and USRN are an underpinning linking mechanism that removes error in data exchange and communication and delivers efficiency gains in operational processes.
•	In the same way that every citizen has a National Insurance number, every Internet-enabled device has an IP address and every book features an ISBN number, every addressable location has a UPRN and every street has a USRN.
•	The UPRN and USRN allows organisations to more effectively and accurately collate, validate and share information based on a common reference, even if there are issues with other reference text associated with a record.
•	Using the UPRN and USRN means that organisations can continue to hold their attribute information in their existing formats but, by adding a single field containing the identifiers, it becomes possible to link matching records in different databases together.

## Expected Benefits
> ●	Adopting the UPRN and USRN and associated geometries as a government standard will create economic value by increasing their use and reducing barriers to valuable use cases, such as housing, network infrastructure planning, conveyancing and underground asset management.
●	Removing these barriers has substantial economic value, and plays a critical role in the market.
●	Local Government is already seeing significant efficiencies, savings and service improvements from the internal and external exchange of information using  UPRNs and USRNs. GeoPlace estimates that local government currently sees a return on investment of 4:1. Case studies and full economic report can be found at www.geoplace.co.uk

## Functional Needs
> The mandate of a single, authoritative, unique, and persistent identifier for addresses and streets.

**Comment by torgo** [comment]
Is there any more detail available on the plan to make these more "open" according to the [Open Standards Principles](https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles)?

**Comment by stevenbrandwood** [comment]
> Is there any more detail available on the plan to make these more "open" according to the [Open Standards Principles](https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles)?

Hi, 
The LGA and GeoPlace are working with the Geospatial Commission on the proposals to release the UPRN and USRN with co-ordinates/geometry as Open - there are a number of conditions that are being discussed to ensure benefits are maximised and any risks reduced. One of which is adoption of the UPRN as a mandatory standard on public sector bodies - hence the application to consider this through the Standards Board.  It's a little chicken and egg so what we are looking for at the moment is an 'in principle' decision from the Standards Board.  The LGA Board are due to meet again in June and we hope the Standards Board can give a positive decision (albeit in principle) to help with the discussion.
The Open UPRN and co-ordinate proposal would mean that these data elements would be royalty free ans available under OGL.  I hope this helps, but please feel free to ask further questions. Steve

**Comment by PeterParslow** [comment]
Do you still have access to the extensive discussion on this subject under the 'old' Data Standards Panel, "Exchange property/place/address information" challenge?

In 2015, it was at http://standards.data.gov.uk/proposal/exchange-propertyplace-address-information-proposal?stage=proposal 

From memory, the conclusion was that this is more about "open data" than "open standards". The discussion stalled on what should be 'returned' when a UPRN is queried. Some wanted 'just' the coordinates; others didn't want (need) the coordinates, but wanted a list of the administrative areas within which the UPRN lays (ward, etc) to support applications around planning & reporting issues to local authorities. Others wanted the full postal address.

From Steven's comment above, it would seem that the Geospatial Commission has made a proposal that may 'crack this nut' - at least if 'co-ordinates' is the answer!

**Comment by Lawrence-G** [comment]
The panel meeting notes are on GitHub[ here ](https://github.com/alphagov/open-standards/blob/master/docs/_meetings/2015%E2%80%9010%E2%80%9023-data-panel-meeting.md)
We have the Board meeting notes [here](https://github.com/alphagov/open-standards/blob/master/docs/_meetings/2015%E2%80%9011%E2%80%9013-open-standards-board.md) 
The NA have the original Hub content [here](https://webarchive.nationalarchives.gov.uk/20150331170133/http://standards.data.gov.uk/challenge/exchange-property-place-information) unfortunately without comments

I have a scrape from the original Hub that includes the comments [here](https://docs.google.com/document/d/1LGokN6FYvDeUG_93J3P64sxi93cCQ-A2Pi18TLwespA/edit?usp=sharing)

**Comment by ravibhojwani** [comment]
Is there any standard used already by Land registry? Im selling a property and waiting for HM Land Registry to register a plot included in the deeds. I know they are experimenting with Blockchain.

**Comment by Lawrence-G** [comment]
@ravibhojwani Blockchain a little out-of-scope here but you may have already seen the dataset That contains [HM Land Registry Title Numbers and AddressBase UPRN](https://www.gov.uk/government/publications/title-number-and-uprn-look-up-dataset-specification/title-number-and-uprn-look-up-dataset-specification)

**Comment by Lawrence-G** [comment]
Our draft assessment of UPRN and USRN is ready for comment - [Here](https://docs.google.com/document/d/1JjprVxuXaZ1k8v-otStqvgvBd6yB1L6l-JFk_mhS7bU/edit?usp=sharing)


The 47 question assessment is a subset of the [CAMSS ](https://ec.europa.eu/isa2/solutions/camss_en)questions

**Comment by Lawrence-G** [comment]
**UPRN USRN Assessment**

## Formal specification


**Q. 1.** Does it address and aid interoperability between public administrations?

**Yes** 

As it enables data that reference a property or street to be linked by a consistent identifier. Existing address and street formats can still be used. Adding a UPRN or USRN to a record enables cross referencing with other databases.
 
**Q. 2.** Does it address and aid the development of digital services in government?

**Yes**

A variety of case studies (both local and central) can be found on GeoPlace’s website: https://www.geoplace.co.uk/helpdesk/library/case-studies


“The UPRN facilitates greater accuracy and immediate data sharing and matching — delivering better services and better outcomes for citizens.” Matt Hancock 2016-5
https://www.gov.uk/government/speeches/geoplace-conference-matt-hancock-speech


**Q. 3.** Are the functional and non-functional requirements for the use and implementation of the specification clearly defined?

**Yes**
As an identifier there are few requirements 
UPRNs and USRNs are integers (numbers) that can be up to 12 digits in length; they can therefore be less than 12 digits long and do not require leading zeros. However, some gazetteer database applications will pad UPRNs and USRNs that are less than 12 digits with zeros.
The use of the ‘official definitive’ UPRNs and USRNs is a fundamental.

**Q. 4.** Is it possible to implement the specification across different domains?

**Yes**

In any domain where an address or a street needs to be recorded in machine-readable format 
usage examples  https://www.geoplace.co.uk/addresses/uprn/the-uprn-in-action


**Q. 5.** Is it largely independent from products of single providers, either open source or proprietary?

**Yes**
The standards are identifiers that can be used in data held in any system used with any product.  The UPRN/USRN themselves are only available from GeoPlace/OS (or their partners), although once Open the assumption is that they will be available via data.gov.

**Q. 6.** Is it largely independent from specific platforms?

**Yes**
A UPRN or USRN is can be used on any platform. 

**Q. 7.** Has the standard been written so that it can be delivered or used with more than one technology (for example XML and JSON)?

**Yes**
A UPRN or USRN can be used with various technologies e.g. spreadsheets, databases, XML/GML schema, APIs and linked data
https://www.geoplace.co.uk/addresses/uprn

**Q. 8.** Has the specification been sufficiently developed and existed long enough to overcome most of its initial problems?

**Yes**

Both identifiers for part of BS7666 which has had periodic reviews over the last 20 years
UPRN has seen real-world use by many organisation over the last 20 years
The USRN has been used for 20 years to enable Utility Companies to provide street works notices to Local Highway Authorities under the New Roads and Street Works Act 

**Q. 9.** Are there existing or planned mechanisms to assess its conformity and implementation - for example conformity tests, certifications and plugfests?

**NA**

**Q.10.** Does it have sufficient detail, consistency and completeness for the use and development of products?

**NA**
These standards are numerical identifiers used in datasets 



## Implementation of the formal specification


**Q. 11.** Does it provide current implementation guidelines and documentation for the implementation of products?

**NA**
The standards are unique identifiers  Geoplace does publish a number of case studies that outline the use of the UPRN and USRN
An example - https://www.geoplace.co.uk/-/-using-the-uprn-as-the-key-to-creating-a-unified-customer-index


**Q. 12.** Does it provide a reference (or open source) implementation?

**No**

**Q. 13.** Does it address backwards compatibility with previous versions?

**NA**

Note - A UPRN or USRN is only used once, and is nationally unique.
Throughout its lifecycle, information on the address of a property can change. This may be due to a change of name, a sub-division or aggregation of an address within a building, change of use, such as from single occupancy to multiple occupancy, or the eventual demolition of the property. All of these historic, alias and provisional addresses are recorded against the same UPRN.
https://www.geoplace.co.uk/documents/10181/41984/2015%20the%20UPRN%20lifecycle%20V3%20%28CMS%20ID%20-%201429701616057%29



**Q. 14**. Are the underlying technologies for implementing it proven, stable and clearly defined?

**NA**
The identifier is a 12 digit number, so in the strictest sense, there are no specific underlying technology requirements for implementation.  However, a considerable number of end-user applications have adopted the identifiers and are being used in critical service delivery systems.





## Openness

**Q. 15.** Is information on the terms and policies for the establishment and operation of the standardisation organisation publicly available?

**Yes**
Geoplace is a public sector limited liability partnership between Ordnance Survey and Local Government Association.  Policies https://www.geoplace.co.uk/about/policies
BSI is responsible for establishing and operating the underlying British Standard BS7666.  BS7666 reviews and compatibility with European and international standards is managed via the BSI committee IST36 - https://standardsdevelopment.bsigroup.com/committees/50001783

**Q. 16.** Is participation in the creation process of the formal specification open to all relevant stakeholders (such as organisations, companies or individuals)?

**Yes**.
BSI is responsible for establishing and operating the underlying British Standard BS7666.  BS7666 reviews and compatibility with European and international standards is managed via the BSI committee IST36 - https://standardsdevelopment.bsigroup.com/committees/50001783

The Association for Geographic Information plays an important role in feeding industry views into the periodic BS7666 reviews and GeoPlace works closely with their Standards Committee to engage with the wider industry - https://www.agi.org.uk/agi-groups/standards-committee/review-of-bs-7666

Implementation within the National Address and National Street Gazetteers is managed by GeoPlace and technical information can be found here (NB, this is full supply chain support rather than the open identifiers proposal):

https://www.geoplace.co.uk/helpdesk/library/technical-guidance-streets

https://www.geoplace.co.uk/helpdesk/library/technical-guidance-addresses

Additionally, OS provide product support for their products that incorporate the identifiers (NB, this is full product support rather than the open identifiers proposal):

https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/products/addressbase-premium.html

https://www.ordnancesurvey.co.uk/business-and-government/products/os-mastermap-highways-network-products.html

**Q. 17.** Is information on the standardisation process publicly available?

**Yes,** 
see 15 and 16 above

**Q. 18.** Is information on the decision-making process for approving formal specifications is publicly available?

**Yes,** 
see 15 and 16 above

**Q. 19.** Are the formal specifications approved in a decision-making process which aims at reaching consensus?

**Yes,** 
see 15 and 16 above

**Q. 20.** Are the formal specifications reviewed using a formal review process with all relevant external stakeholders (such as public consultation)?

**Yes,** 
see 15 and 16 above

**Q. 21.** Can all relevant stakeholders formally appeal or raise objections to the development and approval of formal specifications?

**Yes,** 
see 15 and 16 above

**Q. 22.** Is relevant documentation of the development and approval process of formal specifications publicly available (such as preliminary results and committee meeting notes)?

**Yes** 
See abaove

## Access to the formal specification

**Q. 23**. Is the documentation publicly available for implementation and use at zero or low cost?


**Yes**
GeoPlace and OS provide specifications on the full products which includes details on how UPRNs and USRNs are allocated.  OS are currently consulting with a closed customer group on the Open UPRN specification and will do the same with the Open USRN specification when ready

**Q. 24.** Is the documentation of the intellectual property rights publicly available (is there a clear and complete set of licence terms)?

**Yes**
The intention is to release Open UPRNs and USRNs under an OGL licence with no additional licence terms.

**Q. 25.** Is it licensed on a royalty-free basis?

**Yes**

The current licence arrangements for UPRNs are:
Royalty free for the public sector
“Following an announcement in February 2015, AddressBase internal business use customers, which includes the whole of the public sector, are able to utilise UPRNs on a royalty free and open basis. The benefits in the following local authority case studies have been enabled by utilising the UPRN and the LLPG. See a press release on the announcement.”

Geoplace policy [here](https://www.geoplace.co.uk/-/policy-statement-unique-property-reference-number-uprn)

OS policy [here](https://www.ordnancesurvey.co.uk/about/governance/policies/addressbase-uprn.html)

As noted in this challenge “GeoPlace has been working with the Geospatial Commission to make ‘open’ the URPN and USRN with their appropriate geometries and are seeking to ‘mandate’ the use of these identifiers across government.”  The intention is to release both UPRNs and USRNs with geometries as Open Data under the OGL.  It is likely that the USRN will have an interim licencing policy that would be identical to the current ‘Royalty Free’ policy for UPRNs. 


## Versatility/flexibility of the proposed standard

**Q. 26.** Has the formal specification been used for different implementations by different vendors/suppliers?

**Yes**
Examples  here https://www.geoplace.co.uk/case-studies

**Q. 27**. Has the formal specification been used in different industries, business sectors or functions?

**Yes**
Examples  here https://www.geoplace.co.uk/case-studies

**Q. 28.** Has interoperability been demonstrated across different implementations by different vendors/suppliers?

**Yes**

Examples here: https://www.geoplace.co.uk/case-studies

## End-user effect of the formal specification

**Q. 29.** Do the products that implement it have a significant market share of adoption?

**NA**
The Standards are not used to build products unless the data is considered a product.  Open URPNs and USRNs could be attributed to 3rd party address and street datasets royalty and licence free, although there are concerns that promoting this would undermine the integrity of the standard.


**Q. 30**. Do the products that implement it target a broad spectrum of end-uses?

**Yes**
Examples here:
https://www.geoplace.co.uk/addresses/uprn
https://www.geoplace.co.uk/addresses/uprn/connecting-data
https://www.geoplace.co.uk/streets/managing/what-is-the-nsg

**Q. 31.** Does it have strong support from different interest groups?

**Yes**

**Q. 32.** Is there evidence that the adoption of it supports improving efficiency and effectiveness of organisational process?

**Yes**
See ‘better outcomes’ in this linked page
https://www.geoplace.co.uk/addresses/uprn/connecting-data


**Q. 33.** Is there evidence that the adoption of it makes it easier to migrate between different solutions from different providers?

**Yes**
Consistent identifiers for property addresses will make migration easier - this may increase if the standard is opened up to allow more suppliers to integrate the standard into their product.
An example of consolidating address management systems as part of a local government reorganisation can be[ seen here](https://www.geoplace.co.uk/case-studies?p_p_id=101&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_101_struts_action=%2Fasset_publisher%2Fview_content&_101_returnToFullPageURL=%2Fcase-studies%3F_3_keywords%3Dreorganisation%26p_p_id%3D3%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_3_struts_action%3D%252Fsearch%252Fsearch%26_3_redirect%3D%252Fcase-studies%26_3_groupId%3D10181&_101_assetEntryId=85425&_101_type=content&_101_urlTitle=it-is-more-than-just-partnership-working-it-is-about-providing-one-service&redirect=https%3A%2F%2Fwww.geoplace.co.uk%2Fcase-studies%3Fp_p_id%3D3%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_3_groupId%3D10181%26_3_keywords%3Dmigration%26_3_struts_action%3D%252Fsearch%252Fsearch%26_3_redirect%3D%252Fcase-studies%253F_3_keywords%253Dreorganisation%2526p_p_id%253D3%2526p_p_lifecycle%253D0%2526p_p_state%253Dmaximized%2526p_p_mode%253Dview%2526_3_struts_action%253D%25252Fsearch%25252Fsearch%2526_3_redirect%253D%25252Fcase-studies%2526_3_groupId%253D10181&i)

**Q. 34.** Is there evidence that the adoption of it positively impacts the environment?

**Yes**
An example - Vehicle routes for all waste and recycling were optimised in Northumberland, delivering cashable savings of over £200,000 per year with a consequent reduction in the council's carbon footprint with the majority being fuel savings
https://www.geoplace.co.uk/addresses/uprn

Also [City of Nottingham’s InSmart project](https://www.geoplace.co.uk/en/helpdesk/library/-/asset_publisher/r91RWkfXFemB/content/simulating-the-energy-use-of-buildings-in-the-city-of-nottingham-the-insmart-project)



**Q. 35.** Is there evidence that the adoption of it positively impacts financial costs?

**Yes**
A GeoPlace commissioned study 'Cost Benefit Analysis of Address and Street Data for Local Authorities and Emergency Services in England and Wales', projects net benefits up to £202 million by 2020 from better use of the address and street data that councils create and maintain. Based on the current rates of adoption, this represents a Return on Investment after discounting of 4:1.

https://www.geoplace.co.uk/-/geoplace-identifies-impressive-4-return-on-every-1-spent-on-council-address-and-street-information



**Q. 36.** Is there evidence that the adoption of it positively impacts security?

**No**


**Q. 37.** Is there evidence that the adoption of it can be implemented alongside enterprise security technologies?

**No**
No evidence found

**Q. 38.** Is there evidence that the adoption of it positively impacts privacy?

**No**
None found. There are possible impacts on privacy when linking address data with other information.

**Q. 39.** Is it largely compatible with related (not alternative) formal specifications in the same area of application?

**Yes**
UPRN/USRN can be combined with other identifiers used

**Q. 40.** Is there evidence that the adoption of it positively impacts accessibility and inclusion?

**No** 
None found 

## Maintenance of the formal specification

**Q. 41.** Does it have a defined maintenance organisation?

**Yes**
UPRN  USRN ranges are centrally allocated and managed by GeoPlace a Limited Liability Partnership jointly owned by the Local Government Association (LGA) and Ordnance Survey.

**Q. 42.** Does the maintenance organisation provide sufficient finance and resource to control short-to-medium-term threats?

**Yes**
See OS report 17-18 
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/747829/ordnance-survey-annual-report-accounts-2017-2018-print.pdf


**Q. 43**. Does the maintenance organisation have a public statement on intention to transfer responsibility for maintenance of it, if the organisation were no longer able to continue?

**No**

**Q. 44.** Does it have a defined maintenance and support process?

**NA**

**Q. 45.** Does it have a defined policy for version management?

**NA**

No version management. A UPRN itself is a unique identifier (in fact a 12 digit number) that is valid throughout a property’s life cycle

## Related European standards

**Q. 46.** Is this an existing European standard or an identified technical specification in Europe? (Note: CEN, CENELEC or ETSI are the European standards bodies. Technical specifications provided by organisations other than CEN, CENELEC or ETSI can be under consideration to become a European standard or an identified technical specification in Europe.)

**No**
Note:
BSI ensures compatibility with CEN and ISO standards.  GeoPlace and OS ensure compatibility with INSPIRE Regulation

UPRN and USRN is used in the UK only 

**Q. 47.** Does this specification or standard cover an area different from those already identified or currently under consideration as an identified European standard or specification?

**Yes**
The URPN and USRN applies in England, Wales, Scotland, Northern Ireland, the Channel Islands and the Isle of Man.

**Comment by Lawrence-G** [comment]
This proposal seeks agreement in principle from the [Open Standards Board](https://www.gov.uk/government/groups/open-standards-board) that the UPRN and USRN are adopted as standards on condition of them being made open. Presented by Steven Brandwood and the Open Standards Team.

In their Annual Plan (https://www.gov.uk/government/news/geospatial-commission-outlines-its-2019-2020-priorities), the Geospatial Commission working with OS, Local Government Association, GeoPlace, and the Improvement Service on behalf of Scottish local government to investigate opening up the Unique Property Reference Number and the Unique Street Reference Number (UPRN/USRN) with associated geometry.



## Introduction 

A postal address is a loosely defined set of instructions for a post person. Many government databases use postal addresses to identify geographical locations. Using the traditional form of a postal address in exchange and re-use of data can be problematic due to inconsistency and lack of uniqueness. 

To enable a standard way of defining and exchanging property and street information
the Unique Property Reference Number (UPRN) and the Unique Street Reference Number (USRN) should be used.

These identifiers are attributed by local government to every address and street in Great Britain. They are used to link data and to ensure unambiguous and persistent identification when sharing information related to properties and streets. 

In use with local government and many other public sector bodies, the UPRN and USRN are already providing significant service delivery and efficiency benefits. Use across the public sector will significantly increase these benefits.


## User need approach

Users in this proposal are people or systems in government bodies who record and exchange property and street location data digitally in the UK. 

These users need a persistent, resolvable identifier which is stable over time and easy to exchange between information systems. 

The UPRN and USRN allow organisations to more effectively and accurately collate, validate and share information based on a common reference, even if there are issues with other reference text associated with a record.

When using UPRNs and USRNs organisations can continue to hold information in their existing formats but, by adding a field containing the identifiers, it becomes possible to link matching records in different databases together.



## Achieving the expected benefits

The benefits of using these identifiers are that they promote interoperability and reuse between systems that contain address data.

Adopting the UPRN and USRN as a government standard and consequently increasing their use will create economic value in use cases such as housing, network infrastructure planning, conveyancing and underground asset management. Removing barriers to interoperability has substantial economic value, given, the critical role data plays in these and other markets.

UPRNs and USRNs could be published and referenced by non-public sector bodies to support open data agendas. 


## Functional needs

The proposed solution involves numerical identifiers that work across disparate systems. 
UPRN and USRN:
cover UK Addresses
are single persistent, resolvable, serialisable identifiers which are stable over time and easy to exchange between information systems
allow unambiguous matching between different data sets




## Other steps to achieving interoperability

Systems that publish data sets containing addresses should include the UPRN and USRN.
Applications that consume data sets containing addresses should prefer and promote UPRN and USRN.

**Comment by stevenbrandwood** [comment]
Steven Brandwood
Executive Director of Engagement, GeoPlace LLP

157-197 Buckingham Palace Road
London, SW1W 9SP
steven.brandwood@geoplace.co.uk
07867 975524
t 020 7630 4600 | information line 0843 4620000
@GeoPlaceLLP | www.geoplace.co.uk | https://khub.net

Bringing location to life

GeoPlace is a public sector Limited Liability Partnership (LLP) jointly owned by the Local Government Association and Ordnance Survey - https://www.geoplace.co.uk/disclaimer

**Comment by Lawrence-G** [comment]
Geospatial Commission to release core identifiers under Open Government Licence
see this announcement 
https://www.gov.uk/government/news/geospatial-commission-to-release-core-identifiers-under-open-government-licence

**Comment by james-apex27** [comment]
Hi,

I'm part of a team developing proptech products. We'd really like to make use of the UPRN, so was waiting for the 1st of July with bated breath. However, it would seem the open data only includes the co-ordinates of the UPRN, as opposed to the address.

Using just open data is it possible to take a formatted street address and find a UPRN for that address, conversely is it possible to get a fully formatted address from a UPRN?

James.

**Comment by MikeThacker1** [comment]
> I'm part of a team developing proptech products. We'd really like to make use of the UPRN, so was waiting for the 1st of July with bated breath. However, it would seem the open data only includes the co-ordinates of the UPRN, as opposed to the address.
> 
> Using just open data is it possible to take a formatted street address and find a UPRN for that address, conversely is it possible to get a fully formatted address from a UPRN?
> 

That's exactly my take and I was wondering if I'm missing anything. From what I read, the UPRN is intended to provide a means of linking data that relates to the same property, but it seems that addresses are not published for UPRNs and I'm unclear about whether you can derive and publish UPRN -> address lookups derived from people's open data sources.

**Comment by james-apex27** [comment]
Hi Mike,

I'm afraid I'm cynical, I have a feeling that they're just paying lip service to open-sourcing the data, there's too much money involved in address data from OS and the Post Office.

It's a real shame, because it would be awesome to connect to other proptech solutions with something like a UPRN, I can see amazing value being created for the economy.

However, when all we have access to is the lat/long location of the UPRN rather than it's address it's a bit of a wet squib.

If I'm right then I feel we've missed a great opportunity to open up this data and create some truly innovative tools :(

I'm really hoping I'm wrong and I'm missing something, after all it's only be out a couple of days.

When I spoke to OS they told me to get an address from a UPRN or to get a UPRN from an address I'll need at least a licence for AddressBase Core.

**Comment by MikeThacker1** [comment]
I still see _some_ value in using the UPRN and will propose it as an addition to the Open Referral UK standard. It will help link data on properties and with de-duplication.

I'm just wondering whether, if enough people reference URRNs alongside separately collected address data, will we ultimately be able to derive the equivalent of AddressBase from completely open data?

**Comment by james-apex27** [comment]
I've contacted Rishi Patel in regards to his BLOG post here:

https://mhclgdigital.blog.gov.uk/2020/04/02/unique-property-identifiers-to-be-opened-under-open-government-license/

I'm hoping the government can respond.

If the idea to open the UPRN was to promote businesses and entrepreneurs developing cool and exciting new products that would add to the overall value of the country then what has been released is not fit for purpose.

**Comment by jameseoneill** [comment]
Hi James

Thanks for your comments and sorry for the delay in getting back to you.

You are right, the open release of UPRNs doesn’t include address data. But public sector bodies can now publish their own data with UPRNs against it openly.

You can look up individual UPRNs at https://www.findmyaddress.co.uk and individual USRNs at https://www.findmystreet.co.uk/
 
Developers can get access to address data via OS partners and Geovation. More information about this is available at https://www.ordnancesurvey.co.uk/news/ordnance-survey-transforms-the-way-customers-access-share-and-innovate
 
Hope this helps to clarify the situation. We've edited the UPRN/USRN profile on GOV.UK to make it clearer that the address information is not included in the open data release: https://www.gov.uk/government/publications/open-standards-for-government/identifying-property-and-street-information

Thanks

James

**Comment by james-apex27** [comment]
James,

Many thanks for your response, I appreciate it.

Regards

James.

**Comment by james-apex27** [comment]
> I still see _some_ value in using the UPRN and will propose it as an addition to the Open Referral UK standard. It will help link data on properties and with de-duplication.
> 
> I'm just wondering whether, if enough people reference URRNs alongside separately collected address data, will we ultimately be able to derive the equivalent of AddressBase from completely open data?

Hi Mike,

This is a great idea, I'm going to submit a FOI to my local authority, to see if I can get them to release the UPRN's along with the address data they have, I believe it falls under the remit of an FOI.

I'll update here if I'm successful.

James.

**Comment by Lawrence-G** [comment]
Thank you, everyone, who contributed to this challenge. [The Identifying property and street information profile](https://www.gov.uk/government/publications/open-standards-for-government/identifying-property-and-street-information) has been added to the list of open standards.

**Comment by james-apex27** [comment]
Hi Lawrence-G,

I appreciate you linking "The Identifying property and street information profile" page.

My understanding was that opening up UPRN's would help commercial developers like myself to produce innovative products, where my prop-tech platform could talk to other prop-tech platforms and uniquely identify a property so no chance for error could occur.

In fact, Christopher Pincher MP said of the opening of UPRN's:-

"This is the most powerful boost for the UK PropTech sector in a generation, unlocking new levels of digital innovation on a national scale." 

I would agree with that statement.

However, to conform to the standard we are advised to "Confirm the identifiers are genuine using a trusted source.".

Can you tell me how as a UK prop-tech business, not falling under the Public Sector Geospatial Agreement, I can validate and confirm the identifiers without paying significant licence fee's to access the AddressBase products?

The two sources you cite as being able to confirm record validation, FindMyAddress and FindMyStreet are NOT available to me as a commercial enterprise.

The requirements to license AddrerssBase and the opening of the UPRN under the OGL seem to be counter to one another.

All I want to be able to do is confirm the UPRN of a specific street address and likewise derive a UPRN from a street address. I'm sure this was the intention of opening UPRN's, without it what is the point?

Thank you

James.

**Comment by Lawrence-G** [comment]
Hi James 

Thanks for your feedback. I understand you feel frustrated that addresses are not included in the open data release.

But I do believe it is a significant enhancement for open government data.

Before the new agreement, government departments were not able to republish datasets that included the identifiers under an open government license. There was no open identifier available to link data held in different government data sets. 

This is now possible. There is more information in the Ordnance Survey's open identifiers policy: https://www.ordnancesurvey.co.uk/business-government/tools-support/open-mastermap-programme/open-id-policy

I appreciate that this does not immediately meet the use case you describe but the profile is one of the open standards for government so is aimed primarily at central government departments. We expect to see wider benefits as organisations start to publish their data openly.

Thanks

Lawrence

**Comment by james-apex27** [comment]
Hi Lawrence,

You are right, I do feel frustrated, it seems to me that such an important identifier is locked behind restrictive licencing.

UPRN's were opened to facilitate prop-tech advances, but without the addresses, they are pretty much useless for most prop-tech companies I know.

Considering the noises from the government, specifically the ministry of housing, around the value that could be created by opening this data set, it's very frustrating to see them hobbled in this way.

I read Rishi Patels blog here:

 https://mhclgdigital.blog.gov.uk/2020/04/02/unique-property-identifiers-to-be-opened-under-open-government-license/ 

And was super excited by all of the different ways UPRN's could be used to add value to UK business in the prop-tech industry.

Mr Patel used an analogy comparing the UPRN to a national insurance number or an IP address. But what we have received is not something that would allow us to find the name of a person from a national insurance number, or the type of device linked to an IP address, but more of the shape of the person, or a 3d model of the device connected to an IP address. Useful for some, but pretty much useless for any business case I could think of.

Can I ask a lay persons question? you state:

"Before the new agreement, government departments were not able to republish datasets that included the identifiers under an open government license. There was no open identifier available to link data held in different government data sets"

Does that mean a government department could now publish a dataset that has the UPRN and address data.

The way I read it is that the Addressbase data is still protected, so it cannot be published.

Sorry if I sound bitter, I don't mean to, any open data is great, I just feel like a huge opportunity to drive major innovation in the prop-tech space has been missed.

James.

**Comment by oboswarva** [comment]
> Before the new agreement, government departments were not able to republish datasets that included the identifiers under an open government license. There was no open identifier available to link data held in different government data sets.

That's not actually true, is it Lawrence? 

Public authorities could publish UPRNs in their open datasets under Ordnance Survey's old UPRN policy. https://webarchive.nationalarchives.gov.uk/20190701163525/https://www.ordnancesurvey.co.uk/about/governance/policies/addressbase-uprn.html

ONS and the Environment Agency among others have been publishing UPRNs in open data for years.
