### ISSUE TITLE
Collecting Beneficial Ownership data

### ISSUE THREAD

**Issue by edent** [alphagov/tech-and-data-standards#76]
## Challenge Owners:

**Ben Vandersteen**

Technical Architect | National, International and Research Directorate | Government Digital Service

**Angus Barry**

Product Manager | National, International and Research Directorate | Government Digital Service

**Warren Smith**

Deputy Director | National, International and Research Directorate | Government Digital Service

## Short Description:

Beneficial Ownership data describes the natural person who owns or controls a legal entity (such as a company or a trust), whether they own it directly or indirectly.  The collection and analysis of Beneficial Ownership information is one way of preventing actors creating opaque company structures to hide illegitimate or harmful activities.  Beneficial Ownership data may be used either internally by law enforcement, or by civil society and other companies if it is published.

A growing number of Governments have committed to collecting Beneficial Ownership data, often through legislation.  These include: the US Corporate Transparency Act 2021; the EU, through the [2018 5th Anti-Money Laundering Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1535129253450&uri=CELEX:32018L0843); British Overseas Territories ([Press release 2020](https://www.gov.uk/government/news/british-overseas-territories-commit-to-publishing-further-information-on-company-ownership-in-major-anti-corruption-move)); and other countries acting unilaterally, such as Indonesia and Armenia.

While UK law allows the owners of legal entities to differ from the beneficial owners, the Government has made a series of commitments to collect Beneficial Ownership data.  These include the [People with Significant Control register](https://www.gov.uk/guidance/people-with-significant-control-pscs) containing Beneficial Ownership data for companies, publicly available since 2016, with [recent plans to improve data accuracy](https://www.gov.uk/government/news/reforms-to-companies-house-to-clamp-down-on-fraud-and-give-businesses-greater-confidence-in-transactions).  In 2016, the UK Government also committed that it would:

> Establish a public register of company beneficial ownership information for foreign companies who already own or buy property in the UK, or who bid on UK central government contracts. ([Open Government Partnership 2020](https://www.opengovpartnership.org/members/united-kingdom/commitments/UK0063/))_

The latter aspect of that commitment is repeated in the [2020 Transforming Public Procurement Green Paper](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/943946/Transforming_public_procurement.pdf), which proposes to automatically exclude bidders who do not state their beneficial owner(s).  

We envisage that the Open Standard for Beneficial Ownership data will make use of the UK Government’s future Legal Entity Identifier via adoption of the [ISO 17442-1:2020 standard](https://www.iso.org/standard/78829.html).

The international non-profit organisation Open Ownership has created the [Beneficial Ownership Data Standard](http://standard.openownership.org/en/0.2.0/) (BODS) to meet the need for a data standard covering Beneficial Ownership data.  This standard is at a relatively early stage of development, but has a full data schema and some open source tools ([Data review tool](https://datareview.openownership.org/); [Bluetail red flagging prototype](https://github.com/mysociety/bluetail); [BODS visualisation](https://www.openownership.org/visualisation/visualisation-tool/); [Data translation](https://github.com/openownership/indonesia-bods-mapping); [BODS export](https://github.com/openownership/register#running-a-bods-export)).

This challenge has four objectives:

1. To give the open standards community the opportunity to contribute to the challenge of establishing an Open Standard for Beneficial Ownership data.
2. To provide feedback to Open Ownership on their BODS v0.3, so they can continue to develop it in preparation for their v1.0 release.
3. To coordinate open standards discussions for Beneficial Ownership data in the UK, in advance of new Government commitments to collecting it.
4. To demonstrate to other countries how an Open Standard for Beneficial Ownership data could be created, possibly helping efforts to coordinate standards internationally so that beneficial ownership data could be shared across borders (for example, to assist with international money laundering investigations).

## User needs:

**Procurement**

As a procurement official, I need to know who ultimately benefits from the award of contracts so that I can identify conflicts of interest from companies bidding for public money.  For example, I would need to know if a company’s beneficial owner was a Cabinet Minister, or if all companies bidding shared a beneficial owner (in compliance with anti-bribery and disclosure obligations).

As a procurement official, I need to ensure that disqualified individuals are not involved in government procurements, including by preventing them from delegating named control to another individual or legal entity.

As a procurement official/risk officer, I need to have visibility over supplier ownership structures so that I can identify possible contagion in the case of counterparty, credit or liquidity risk which may impact the supply chain and prevent contracts from being executed and/or legal obligations fulfilled accordingly.

As a compliance officer, I need to ensure that procurement officials do not themselves have an interest in a procurement which they have influence over.

**Counter-fraud**

As public sector service supporting businesses, I need to understand the ownership structure of those businesses so I can ensure those seeking support meet eligibility criteria.

As a public sector service supporting individuals, I need to understand the legal entities and assets that individual(s) or other legal entities control so I can ensure those seeking government support meet relevant eligibility criteria and the risk of identity fraud/theft can be reduced.

**Anti-money laundering**

As a financial services provider, I need to prevent politically exposed persons (PEPs), sanctioned individuals or organisations from being able to access my services, so that I can meet my legal obligations to prevent money laundering, benefit from proceeds of crime or support compliance with other anti-corruption/bribery measures.

As a law enforcement official, I need to be able to trace the ownership of assets and financial flows across borders and remove any impediment or friction in having access to and/or being able to link up or draw comparisons between datasets.

**National security**

As a Government, I need to identify whether those seeking to control companies which are important for national security have connections which present security risks to sensitive sectors of the UK economy or key national infrastructure assets.  For example, the beneficial owner of a company seeking to buy a stake in an arms manufacturer may be connected to the Government of a hostile state.

**Recent reports with supporting evidence**

BEIS’s [2019 Review of the implementation of the People of Significant Control Register](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/822823/review-implementation-psc-register.pdf) found that company ownership data was valued by businesses (22% of those surveyed had used the Register), law enforcement (100% of those surveyed had used the Register to inform investigations), and civil society (100% of those surveyed had used the Register).  A large majority believed the Register had been an improvement.  Those who disagreed cited issues such as poor data validation and verification, and the lack of an identifier for individuals.

The scale and nature of economic crime in the UK is analysed in this 2020 House of Commons Briefing Paper: [Economic crime in the UK: a multi-billion pound problem](http://researchbriefings.files.parliament.uk/documents/CBP-9013/CBP-9013.pdf).

## Expected Benefits:

1. **Efficiency and quality of implementation.**

In addition to the direct user needs concerning Beneficial Ownership data described above, there are a number of needs relating to efficiency and quality in implementing Beneficial Ownership legislation:

*   As a Government seeking to collect Beneficial Ownership data, I need to focus on needs specific to my context, not those which are common to all Governments.
*   As a software developer / data analyst, I prefer working with normalised data.
*   As a software developer / data analyst, I need data to be standardised according to a common format so that I can create automated integrations for datasets.  This is important for Beneficial Ownership data because investigations may cross national boundaries, and because companies may provide Beneficial Ownership data to different parts of Government (for example, during company registration, extractive licensing, or procurement bidding).
*   As an organisation implementing Beneficial Ownership, I need access to expert advice about how to structure data, common components which can support delivery, and the ability to integrate my data with other Beneficial Ownership datasets.
*   As a civil society member, I need Beneficial Ownership data from different sources to be comparable so I can compare corruption risks, and follow financial flows between datasets.

2. **Broader economic efficiency**

The user needs above directly relate to preventing corruption, money laundering and security risks from state-sponsored takeovers.  Current efforts to combat those have introduced extremely large frictions.  For example, compliance with anti-money laundering legislation currently costs an estimated $304 billion globally ([Pol 2020](https://www.tandfonline.com/doi/full/10.1080/25741292.2020.1725366)).  Providing an alternative method for meeting those user needs may allow those frictions to be reduced.

3. **Company registration efficiency**

If implemented effectively, Beneficial Ownership registers undercut the central logic of money laundering - that illicit finances can be hidden behind complex webs of legal entities.  Removing that will reduce the pool of companies which Governments need to monitor.

4. **International coordination**

The immediate motivation for submitting this Challenge is to establish an Open Standard for Beneficial Ownership before it starts being collected more widely, thereby reducing the risks of retrofitting datasets.  Many countries are at a similar stage, facing similar challenges.  

We envisage that our work to establish a UK Beneficial Ownership Open Standard can support other countries through shared lessons, and possibly help solve the coordination challenge.  Money laundering is a cross-border challenge; international collaboration is preferable, including standardisation where appropriate to support data portability.

## Functional Needs:

1. The name and URL link of the proposed open standard or standards

We expect Open Ownership will submit their [Beneficial Ownership Data Standard](http://standard.openownership.org/en/0.2.0/) to the Challenge, and look forward to community feedback.  We are also open to others submitting full or partial solutions.

2. A summary of how the proposed open standard or standards will meet the user’s needs

All the user needs require the ability to connect a legal entity to the person who ultimately controls it, cutting out any shell companies, named directors or other individuals representing an anonymous owner.  This is what Beneficial Ownership data seeks to provide.  

The data interoperability provided by an Open Data Standard is important as users need to be able to follow the trail of money and assets between different parts of the economy, and across international borders.

Many countries have committed to collecting Beneficial Ownership data, and whilst implementation is at an early stage, this creates a window of opportunity to align standards before implementation, rather than retrospectively.

3. Include a summary of your answers to the assessment questions, for example, the maturity and openness of the standard, any intellectual property rights and market support

Open Ownership’s BODS is open source, licensed under the Apache License, Version 2.0.  It is currently at v0.3, with plans to release v1.0 in 2022.  We envisage the Open Standards Challenge process as a way to gather feedback on Open Ownership’s approach and invite contributions from other sources.

4. The predicted benefits and opportunities of using the proposed open standard/s, for example, economic and environmental areas

This is covered in the ‘Expected Benefits’ section.

5. How the open standard or standards can help cross-government interoperability

The principal practical objective of using a beneficial ownership data standard is to ensure interoperability to allow those collecting, using and publishing Beneficial Ownership information to exchange data in a normalised, standardised format.  By setting a common standard of interoperability both across the UK economy and internationally, transparency objectives can be more easily met.

6. Should government organisations be using all or some of the standard?

This is something we would like to explore during the Challenge.  Intuitively we expect there to be some differences based on how legal entities vary according to country.  It may also be important for some government organisations to extend the core of the standard, for example to combine Beneficial Ownership data with procurement data, asset declaration data, registers of lobbying organisations, or Politically-Exposed Persons (PEP) data, etc., or to accommodate existing identifier systems.

7. Are there any legal areas the government will need to consider, such as relevant legislation, public procurement law, intellectual property rights and licensing?

Yes.  This Challenge has been primarily prompted by the publication of the Transforming Public Procurement Green Paper. We expect it also to inform the adoption of any recommendations following the [Corporate Transparency and Register Reform](https://www.gov.uk/government/consultations/corporate-transparency-and-register-reform) consultation. In other countries, the collection of Beneficial Ownership data will usually be governed by legislation.

8. Are there any potential technical barriers the government will need to consider?

HM Government, the Devolved Administrations, Crown Dependencies and the British Overseas Territories will need to consider where and how company data is currently collected and published, and how this Beneficial Ownership data standard can be implemented in their jurisdictions, for example via their Corporate or Ultimate Beneficial Ownership Registers.

9. Are there any operational or non-technical barriers to using the standard and how might they be addressed?

There are broader issues with collecting Beneficial Ownership data, including how to comply with data privacy laws, how to verify the accuracy of submitted data, the process during which legal entities submit Beneficial Ownership data, and how frequently the data must be updated.  These do not affect the logic of establishing an Open Standard, but must be addressed if the implementation of an Open Standard is to be effective.

10. Are there any known issues with backwards compatibility between versions of the standards or with legacy technology?

There are no previous standards governing Beneficial Ownership data.  Compatibility with legacy technology is currently unknown.

11. Are there any known risks government organisations would need to mitigate?

Beneficial Ownership should simplify the company registration landscape.  However, there are possible risks associated with the burden providing Beneficial Ownership data will place on legal entities who have to declare their ownership data.  We expect these to be highlighted during the consultation for the Transforming Public Procurement Green Paper as well as the approach to implement the recommendations of the Corporate Transparency and Register Reform consultation.

12. Have there been any trials, case studies or pilot projects showing the standard in action?

Open Ownership has provided technical support to countries implementing beneficial ownership registers with BODS functionality, including two that are due for launch in 2021. Armenia has built a sector-specific disclosure system for extractives companies, to be rolled out to the wider economy over the next year, which will include BODS-formatted data. Latvia has built a whole economy disclosure system to comply with the EU’s Fifth Anti-Money Laundering Directive and will be publishing in BODS format. The Open Ownership register is an example of transforming existing disclosures to BODS, and includes declarations from three national registries, a procurement register and the extractives sector.  Pilot resources for collecting BODS-compatible beneficial ownership data have been developed for the extractives sector.    

13. Were any other standards considered to solve this challenge? If so, why were they rejected?

We have identified three related data standards:

1. The OECD’s Common Reporting Standard allows for reporting of beneficiaries of trusts and accounts (therefore covering a sub-domain of the scope of this Challenge).  We expect this to be a useful complement to a full Open Standard for Beneficial Ownership by supporting red flag analysis.
2. The [Financial Industry Business Ontology’s data model](https://spec.edmcouncil.org/fibo/ontology/BE/OwnershipAndControl/CorporateOwnership/BeneficialOwner) can describe Beneficial Ownership relationships.  Our assessment is that it is not granular enough for most risk-based analysis.
3. The Open Contracting Data Standard has a [Shareholders extension](https://extensions.open-contracting.org/en/extensions/shareholders/master/) which allows the publishing organisation to provide free text descriptions of ownership information as a temporary solution.  The [Bluetail prototype](https://bluetail.herokuapp.com/) demonstrates how OCDS and Beneficial Ownership data can be combined. 

We are open to all contributions which might be provided through this Open Standards Challenge. In providing input to this Challenge, you should consider:

1. Whether there are user needs we have not included, or whether those we have included need refining or validating.
 
2. The degree to which [Open Ownership’s Beneficial Ownership Data Standard](http://standard.openownership.org/en/0.2.0/) meets our established user needs, and what improvements could be made to it.
 
3. Any technical improvements that could be made to Open Ownership’s Beneficial Ownership Data Standard in advance of version 1.0.
 
4. Whether open source tools could be developed to support the use of an open standard for beneficial ownership data.
 
5. Alternative approaches to identifying a beneficial ownership data standard that could be taken.
 
6. How establishing an open standard for beneficial ownership data in the UK could help cross-government interoperability so that beneficial ownership data could be shared across international borders.

**Comment by edent** [comment]
CC @warrendangersmith

**Comment by anaylo** [comment]
A further user need which pertains to the CQC’s remit re market stability and reference to the standard is outlined: https://futurecarecapital.org.uk/research/data-that-cares/

**Comment by IanJBRE** [comment]
Regulators that are  independent of Government, such as the Gambling Commission, the  Gangmasters and Labour Abuse Authority, and the Financial Conduct Authority could have use cases related to their regulatory remits.

**Comment by giacomomasoncma** [comment]
Adding to waht @IanJBRE says above, the Competition and Markets Authority (where I work) is another regulator that could benefit from a clear picture of beneficial ownership for certain firms/sectors when looking into competition or antitrust issues.

There's also the rather obvious use case by journalists when investigating stories about white collar crime and malpractice (both in private sector and in government).

**Comment by HeliosAnavatis** [comment]
Crown Commercial Service is working on a replacement to the [Supplier Registration Service](https://supplierregistration.cabinetoffice.gov.uk/).  This will include an [OCDS](https://standard.open-contracting.org/latest/en/)-compliant index of entities (both buyers and suppliers) who have 'signed up' to do business with the UK public sector.  

Identities will be pulled from a number of source registries (initially Companies House, a commercial registry and the three national charity regulators).  The initial project phase concentrates on this index and on collecting responses to SQ questions (in a 'tell us once' form) but the second phase requirements include the ability to report on beneficial ownership of bidders to procurement teams (both within CCS and across the UK public sector).  The ability to pull that information from potentially multiple sources, collate it and report on it in a consistent and open format is invaluable to us.

OCDS is a mandated requirement for us and therefore we'll only be able to work with a BO standard which is OCDS-compliant.

**Comment by cyberdudeuk** [comment]
Hello, @anaylo @IanJBRE @giacomomasoncma @HeliosAnavatis - I wanted to acknowledge and thank you for your contributions so far despite the belated follow-up. Your input is very valuable and we're looking to follow-up individually or as a group within the next 2 weeks. Behind the scenes, we've been busy looking at ways of feeding this input more formally into the consultation review process going forward. I will be in touch individually initially and would appreciate if you could provide your contact details through the DSA mailbox so we can arrange follow-up meetings. Many thanks! data-standards-authority@digital.cabinet-office.gov.uk

**Comment by cangong** [comment]
Hello all, we are from the Global Legal Entity Identifier Foundation (GLEIF), and we are very happy to provide comments to this challenge. We will focus the comments on how the Legal Entity Identifier (LEI), a globally recognized open standard for legal entity identification, can establish the first foundational step for the beneficial ownership data collection and facilitate an efficient data collection, aggregation and exchange.

For the ease of reading, we attach the response document below.
[2021-04-28_GLEIF-Response-to-UK Gov Open Standards GitHub Challenge on Beneficial Ownership_v1.0.pdf](https://github.com/alphagov/open-standards/files/6441024/2021-04-28_GLEIF-Response-to-UK.Gov.Open.Standards.GitHub.Challenge.on.Beneficial.Ownership_v1.0.pdf)

Thank you all very much!

**Comment by kd-ods** [comment]
The input above has been really thought-provoking. It's good to see the GLEIF here underlining the centrality of identifiers to data collection. Here's the Open Ownership submission of BODS to the challenge.

### Submission of the Beneficial Ownership Data Standard to the challenge

#### Introduction
The [Beneficial Ownership Data Standard (BODS)](http://standard.openownership.org) provides a structured data format, along with guidance for collecting, sharing and using data on beneficial ownership. The standard is still in development, with the current version being 0.2. The primary format for BODS data is JSON.

We welcome this Data Standards Authority challenge and the above work already done by team members to review the features and suitability of BODS. Open Ownership is happy to submit the following as evidence that BODS can meet the needs identified above.

#### How BODS meets users needs and delivers benefits

**Expressing the connection between company and beneficial owner**
All of the user needs identified in the challenge require a data standard that connects companies (or legal entities more generally) to the natural persons who own or control them. The connection must be clear regardless of any intermediary entities or arrangements (such as shell companies) which mediate the relationship. A statement of beneficial ownership must be able to describe who the beneficial owner is and who the declaring or controlled entity is.

**BODS** meets this user need by connecting an _entity statement_ (describing a company or other legal entity) to a _person statement_ (which describes a natural person) via an _ownership-or-control statement_.

BODS can use this pattern to represent direct beneficial ownership (where the legal owner of a legal entity is the **same** as the beneficial owner) and indirect beneficial ownership (where the legal owner is **not** the beneficial owner).

**Representing company ownership and control structures**
Some of the user needs identified in the challenge require a data standard that describes the ownership structure through which control is exercised. That is, a statement about beneficial ownership must be backed up with information about any chain of intermediaries: legal entities, agreements or arrangements that sit between the legal owner(s) and the beneficial owner. The information must include the identities of the intermediaries plus and their relationships to each other.

**BODS** provides a structured, yet flexible, format for expressing the networks and chains of intermediaries through which control can be exercised. It can represent a full range of intermediary legal entities, legal arrangements and other agreements; for example: trusts, contractual arrangements, and nominee-based shareholding. 

As BODS develops to v1.0 we will consider how, and whether, to expand and represent specific entity types.

**Expressing methods of company control**
Some of the user needs identified in the data standard challenge require a data standard that describes how control is exercised.

**BODS** includes an extensive list of control types, including: appointments to the board of directors, voting rights, informal control, control emerging from contracts and control based on trust roles. This list has expanded as more jurisdictions have sought to bring transparency to beneficial ownership. While there are likely to be changes as more countries build beneficial ownership declaration systems, we expect that the stability of the list will increase as this domain matures.

**Unambiguously identifying individuals and companies**
All of the user needs outlined in the data standard challenge require identifying natural and legal persons unambiguously or, where this is not possible, reducing the uncertainty around their identity. Relatedly, there is a need to identify and flag individuals and entities as politically exposed persons (PEPs) or otherwise linked to state operations.

**BODS** approaches this in two ways. First, the ‘identifiers’ field of entity and person statements allows for the inclusion of multiple identifiers. For example, a national ID number, a passport number or tax identification number for an individual. (Or - where public information must be redacted for privacy’s sake - an internal ID can be published which assists in disambiguation.) For the identification of entities, BODS, like the Open Contracting Data Standard (OCDS), makes use of [org-id.guide](http://org-id.guide/) to identify a company register or other identification scheme (like GLEIF’s LEI). Together, an entity’s registration number and the org-id code for the issuing authority uniquely identify the entity.

Secondly, BODS’ structuring of data allows for disambiguation on a probabilistic basis. It breaks down names, for example, into ‘Full name’, ‘Family name’, ‘Given names’ fields, plus allows for former and alternative names to be included. This aids the job of cross-referencing different records and ascertaining whether they are likely to pertain to the same individual. This approach is one which is used by Open Ownership’s own [Global Register](https://register.openownership.org/).

Where necessary, BODS also allows individuals to be flagged as PEPs and details of their political or state role to be published.
Upcoming developments of BODS will also allow for better representation and identification of state-owned enterprises (SOEs). Clarity about the ownership and control of these enterprises and the extent of their operations is crucial on a [number of fronts](https://www.openownership.org/blogs/state-owned-enterprises-a-new-frontier/).

**Building in interoperability**
Most of the use cases in the data standards challenge require some level of interoperability, either with other beneficial ownership data or with related data sets.

Interoperability is a core design principle for **BODS**, in part because beneficial ownership data requires comparison with other datasets for many use cases to be effective. Useful insights can be gained from bringing BODS-compliant data together with a huge variety of information: financial transactions data, public procurement and contracting information, registers of interest of public officials, licensing and regulatory systems. For example, the Sinar Project's investigative platform [Politikus](https://github.com/Sinar/politikus), combines BODS, OCDS and Popolo data.

One cornerstone of this interoperability is the use of good quality personal and company identifiers (touched on above). It is critical for publishers to get this right, and the structure of BODS helps them to do so.

A further cornerstone is ensuring that relevant aspects of the BODS schema are aligned with other data standards; for example [Popolo](http://www.popoloproject.com/), the [EC ISA Core Person vocabulary](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/e-government-core-vocabularies/core-person-vocabulary), and the OECD’s [Common Reporting Standard](https://www.oecd.org/tax/exchange-of-tax-information/common-reporting-standard-xml-schema-user-guide-for-tax-administrations-june-2019.pdf) (CRS).

Finally, the BODS schema draws on existing codelists and standards where possible. For example: ISO 8601 for date formats, and ISO 3166 for 2-digit country codes.

**Supporting verification**
All of the use cases identified in the data standards challenge require data that is high-quality and, preferably, verified. That is, the data standard must allow users of beneficial ownership data to judge the veracity of the information, particularly when this comes from multiple sources.

**BODS** allows information sources and verification details to be represented in a statement. Annotations can be added to any field within a statement to provide additional information.

We expect to do more work exploring whether verification details should be further and usefully structured within the schema as BODS moves to 1.0. This would be based on learning from countries implementing beneficial ownership declaration systems and would build on our [current thinking](https://www.openownership.org/uploads/OpenOwnership%20Verification%20Briefing.pdf) about verification in this domain.

#### And finally...
Declaration of beneficial ownership information and its sharing and use is still in its infancy. We know that the full value of beneficial ownership information will come from sharing data across borders. With BODS only at version 0.2, it has time to develop and mature in response to global developments and requirements in this field, while meeting local needs. Open Ownership would welcome the UK’s adoption of the standard.

**Comment by nadya-GH** [comment]
Hi @kd-ods , 
Thanks for your input and apologies for the delayed acknowledgment. Would you be happy to have a chat with the team at the Data Standards Authority? If so, could you please drop us a line with your availability for next week to our DSA mailbox, data-standards-authority@digital.cabinet-office.gov.uk ? Or share your email here and I'll be in touch. 
Many thanks,
Nadya
Policy and Engagement Lead,
DSA

**Comment by kd-ods** [comment]
@nadya-GH I'm just noting here, for the benefit of those following the thread, that I've been in touch and am in contact with the DSA team.

**Comment by ianmakgill** [comment]
@edent there's use case for the Construction and Technology Court (https://www.gov.uk/courts-tribunals/technology-and-construction-court) which handles many of the corporate cases in the UK. Currently the court uses company names in all of its documents, however, there's no ready way for users of their data to extrapolate that to either a company record or a beneficial ownership record.
On the matter of efficacy of implementation, this is really critical, currently the chain of ownership that is described in PSC data doesn't have full referential integrity for company numbers (inconsistent company names are being used to link records). For users to be able to build services on top of this data (e.g. procurement databases) it is vital that there is robust, trustworthy data with referential integrity and good metadata being provided at source. So it is not enough to say "we have compliant data", it needs to meet quality standards too, so that people can build services on top of the data.
The benefits of adopting BODS as an open standard allows for effective interchange and linking of numerous datasets. One clear example has been the publication of gender disparity data using a company number, that means that it is much more likely that this secondary data can be used by data analysts (e.g. https://spendnetwork.com/gender). With well structured data on BODs it becomes possible to assess the behaviour of a whole group of companies provided the data is linkable. This provision means that companies can be held to account more easily, but also that they can report their organisation and tax status more easily.

**Comment by cyberdudeuk** [comment]
Add to Proposal link to **Order In Council**, FCDO [Policy paper](https://www.gov.uk/government/publications/overseas-territories-adopting-publicly-accessible-registers-of-beneficial-ownership/overseas-territories-progress-made-on-improving-transparency-and-addressing-illicit-finance-flows-explanatory-note#draft-order-in-council) - **"Overseas Territories: progress made on improving transparency and addressing illicit finance flows - explanatory note"** - Published 14 December 2020

1) Following the commitments from all of the inhabited Overseas Territories (OTs) to adopt publicly accessible registers of company beneficial ownership, this paper accompanies a draft Order in Council published under the Sanctions and Anti-Money Laundering Act 2018 (SAMLA). It sets out the main provisions in the Order and the UK Government’s expectations of the OTs’ registers; the progress the Territories have made in addressing illicit finance flows and improving transparency in their jurisdictions; and our collective next steps.

2) All of the OTs with financial centres already share confidential information on company beneficial ownership and tax information with UK law enforcement bodies in real time, and have now all agreed to introduce publicly accessible registers of company beneficial ownership, with the British Virgin Islands (BVI) committing to the policy recently. This represents a major change, led by the OTs. Earlier this year Transparency International welcomed the co-operation that the UK receives from the OTs and their “commitment to end corporate secrecy in their jurisdictions ” [footnote 1].

3) The UK Government expects the Territories’ registers to be in place by the end of 2023

**[Draft_SAMLA_s51_Order.odt](https://github.com/alphagov/open-standards/files/6747762/Draft_SAMLA_s51_Order.odt)**.

**Comment by DidacFB-CDDO** [comment]
As per housekeeping practices we are closing this with the status as a recommended standard.
